### ISSUE TITLE
Preview of work-in-progress narratives for translators

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#100]
The translators of our 2019-nCoV narratives would benefit from a way to preview their work-in-progress.

Possible solutions:

* ~Use the `staging` branch of github.com/nextstrain/narratives by frequently merging the topic branches containing translators edits to `staging`. Requires no code changes.~ This won't work well because narratives are first developed in nextstrain/ncov and then copied to nextstrain/narratives.

* Support a way to specify an alternate Git branch for /community URLs and use on something like `/community/nextstrain/narratives@some-other-branch/…`. Or possibly via a `?branch=` query parameter. The `user/repo@branch` syntax, however, is common in other places that use Git urls. Requires code changes to `CommunitySource` in `nextstrain/nextstrain.org`.

* Something with Heroku review apps?

Option 2 seems like the winner. [Slack discussion](https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1580168147018500).

**Comment by trvrb** [comment]
I like option 2. with `user/repo@branch`.

**Comment by tsibley** [comment]
Implemented in #102.
