### ISSUE TITLE
help debug error from /fetch/ ?

### ISSUE THREAD

**Issue by AngieHinrichs** [nextstrain/nextstrain.org#1026]
### Current Behavior
The URL https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json displays an  error banner:

> There seems to have been an error accessing that dataset.
> Details: Couldn't load JSONs for fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json . Please [contact us](https://nextstrain.org/contact) if you think this is a bug.

The JS console shows this:
```
auspice.chunk.124.bu…07bd805ed7b8e2.js:2 
 GET https://nextstrain.org/charon/getDataset?prefix=fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json 500 (Internal Server Error)
auspice.chunk.124.bu…07bd805ed7b8e2.js:2 n: /charon/getDataset?prefix=fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json {"error":"request to https://hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json failed, reason: "} (Internal Server Error)
    at https://nextstrain.org/dist/auspice.chunk.124.bundle.7e58ac0….js:2:317225
    at d (https://nextstrain.org/dist/auspice.chunk.124.bundle.7e58ac0….js:2:310542)
    at Generator.<anonymous> (https://nextstrain.org/dist/auspice.chunk.124.bundle.7e58ac0….js:2:311897)
    at Generator.next (https://nextstrain.org/dist/auspice.chunk.124.bundle.7e58ac0….js:2:310905)
    at a (https://nextstrain.org/dist/auspice.chunk.124.bundle.7e58ac0….js:2:316550)
    at c (https://nextstrain.org/dist/auspice.chunk.124.bundle.7e58ac0….js:2:316753) '/charon/getDataset?prefix=fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json {"error":"request to https://hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json failed, reason: "} (Internal Server Error)'
```

I am able to download the JSON file directly from https://hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json without error.  

I am also able to download the JSON using the charon URL shown in the JS console:
https://nextstrain.org/charon/getDataset?prefix=fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json

jq is able to parse the downloaded subtreeAuspice1_genome_test_336f6_7eda80.json without error, so my JSON isn't completely broken, although there might still be some kind of issue in terms of correctness for Auspice?

### Expected behavior
I expect https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json to display a tree (or maybe show something more informative in the JS console about why it's failing).

### How to reproduce
Open dev tools and visit https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json

### Possible solution
You instantly see the problem with my JSON and tell me how to fix it 🙂 

### Your environment: if browsing Nextstrain online
 - Operating system: MacOS Ventura 13.6.4
 - Browser: Chrome 128.0.6613.120

### Your environment: if running Nextstrain locally
N/A

### Additional context
Thanks @FedeGueli for alerting me to the failure.

**Comment by AngieHinrichs** [comment]
Wait, it just started working.  https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json shows me a tree now.  That was fast, thanks!

**Comment by jameshadfield** [comment]
Nothing's changed with nextstrain.org / auspice over the past two hours, so my guess is changes on your side. Currently the auspice view and [the charon URL](https://nextstrain.org/charon/getDataset?prefix=fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json) aren't working (500 error), while [a direct call to hgwdev](https://hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json) returns the JSON just fine.

Here are the salient (but perhaps unhelpful) server logs for the failing charon call:
```console
GET https://hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json (cache: no-cache)

heroku[router]: at=info method=GET path="/charon/getDataset?prefix=fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json" host=nextstrain.org request_id=*** fwd=*** dyno=web.2 connect=1ms service=422ms status=500 bytes=606 protocol=https

[warning]	Failed to fetch v2 main JSON: FetchError: request to https://hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json failed, reason: 
```

**Comment by AngieHinrichs** [comment]
Thanks!

At the moment the [charon URL](https://nextstrain.org/charon/getDataset?prefix=fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json) works OK and so does the [/fetch/ URL](https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_336f6_7eda80.json).  But if you saw a failure from charon then there may still be something intermittent going on with charon or hgwdev.  I'll close this for now and re-open if I observe something that looks repeatable.

**Comment by AngieHinrichs** [comment]
P.S. FWIW, the hgwdev server logs show requests for the file with no errors -- mostly HTTP 200 results with one HTTP 304 (Not Modified).
