### ISSUE TITLE
/pathogens: Add tiles for all pathogens

### ISSUE THREAD

**Issue by victorlin** [nextstrain/nextstrain.org#1033]
_continuing from https://github.com/nextstrain/nextstrain.org/issues/940#issuecomment-2362591309_:

> the best thing for nextstrain.org/pathogens is to include a tile for every pathogen

## Tasks

- [ ] Add missing entries for Lassa, Seasonal cov, Tuberculosis, West Nile Virus, Nextclade (?)
- [ ] Sort alphabetically
- [ ] Rename "Showcase" to something else (since it is all listings, not a select few as originally intended)

**Comment by victorlin** [comment]
`nextclade/sars-cov-2` is an odd one:

![image](https://github.com/user-attachments/assets/8c6197eb-a3a2-4054-a71c-e55b07a84e03)

Maybe it can be represented by a tile like `SARS-CoV-2 (Nextclade)`? This would only make sense as long as there is no other `nextclade/*`.

**Comment by trvrb** [comment]
My desire would be for every nextclade dataset to be represented at `/nextclade`. Right now I find myself going to clades.nextstrain.org and picking a reference pathogen and example dataset if I want to see the nextclade reference tree for a particular nextclade dataset. I don't know how easy including an automated push to data.nextstrain.org as part of the release process for nextclade datasets would be. Having these pushed to data.nextstrain.org would have the added benefit of easily looking at past versions, eg https://nextstrain.org/nextclade/sars-cov-2@2024-01-01 cc @rneher and @corneliusroemer 

@victorlin: My sense is that a tile that says `SARS-CoV-2 (Nextclade)` is a fine solution for your PR. It may get revised revised to `Nextclade` in the future.

**Comment by victorlin** [comment]
> My desire would be for every nextclade dataset to be represented at `/nextclade`…

Continuing in #1037
