### ISSUE TITLE
type error in nav/nav-logo.tsx

### ISSUE THREAD

**Issue by genehack** [nextstrain/nextstrain.org#1072]
@genehack could you look into this [type error](https://github.com/nextstrain/nextstrain.org/actions/runs/11826364406/job/32952189773#step:5:10)? It's related to changes from https://github.com/nextstrain/nextstrain.org/pull/1032

```
Error: components/nav/nav-logo.tsx(25,12): error TS2322: Type '{ src: string; }' is not assignable to type 'string | StaticImport'.
  Type '{ src: string; }' is missing the following properties from type 'StaticImageData': height, width
```

_Originally posted by @victorlin in https://github.com/nextstrain/nextstrain.org/pull/1070#discussion_r1841231752_

**Comment by victorlin** [comment]
I just checked locally and also don't see it. But CI on GitHub Actions is consistently showing the error on the PR. I did some [inspection](https://github.com/nextstrain/nextstrain.org/actions/runs/11923742872/job/33232726141):

- It's also using version 5.4.5 (from package-lock.json).
- The type declarations from next.js are the same as what I have locally.
- I tried removing the img type declaration with 80e36d6892b188c27e9fbaaa052d4b3c132dbcb8. `tsc` runs without error locally but the GitHub Actions run shows several `Cannot find module '…' or its corresponding type declarations.`.

Not sure how to explain the difference...

**Comment by genehack** [comment]
> I just checked locally and also don't see it. But CI on GitHub Actions is consistently showing the error on the PR. I did some [inspection](https://github.com/nextstrain/nextstrain.org/actions/runs/11923742872/job/33232726141):
> 
>     * It's also using version 5.4.5 (from package-lock.json).
> 
>     * The type declarations from next.js are the same as what I have locally.
> 
>     * I tried removing the img type declaration with [80e36d6](https://github.com/nextstrain/nextstrain.org/commit/80e36d6892b188c27e9fbaaa052d4b3c132dbcb8). `tsc` runs without error locally but the GitHub Actions run shows several `Cannot find module '…' or its corresponding type declarations.`.
> 
> 
> Not sure how to explain the difference...

I'll try to futz with it further…

**Comment by genehack** [comment]
So, I don't know why, but 1143569951acff9a693c2cabda3398fdfa86a246 fixes the type error in the GH Action — do you just want to cherry-pick that into your active branch for type fixes?

**Comment by genehack** [comment]
> ~`src={logo}` can be retained~ oh, [nevermind](https://github.com/nextstrain/nextstrain.org/actions/runs/11940242691/job/33282481804)

😆 yeah, i tried that; sorry i didn't mention it more explicitly.

**Comment by victorlin** [comment]
I dug a little deeper and figured out why it was working locally but not on GitHub Actions: https://github.com/vercel/next.js/issues/53959

The image type provided by Next.js:

```ts
declare module '*.png' {
  const content: import('../dist/shared/lib/image-external').StaticImageData

  export default content
}
```

is made available by `static-site/next-env.d.ts` which is only available after build. I think the proper solution is to update CI with a build before type checking.

I was then confused because this allows the current usage of `width` without `height` which goes against the docs. But I realized that it's not actually enforced by the type definition for the `Image` component:

```ts
    width?: number | `${number}` | undefined;
    height?: number | `${number}` | undefined;
```

I'll still add `height` here just to align with docs.
