### ISSUE TITLE
getAvailable API request bug for community datasets

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#121]
The `request` field is not correct for `getAvailable` API requests with community datasets. This manifests in auspice not correctly displaying the "built with" text.

E.g. https://nextstrain.org/charon/getAvailable?prefix=/community/blab/zika-colombia returns:
```json
"datasets": [
    {"request": "community/blab/zika-colombia/zika-colombia"
```
But the request should be `community/blab/zika-colombia`.

Bisecting indicates this bug arrived in 94973fc2017071dabb01d3e3cc6c65bbfaafee66

**Comment by victorlin** [comment]
Just made a PR with a potential fix for this. A better example might be one with a non-master branch (e.g. https://nextstrain.org/charon/getAvailable?prefix=/community/blab/ebola-narrative-ms@new-narrative):

    "datasets": [
        {"request": "community/blab/ebola-narrative-ms@new-narrative/ebola-narrative-ms",
         "buildUrl": "https://github.com/blab/ebola-narrative-ms"

The PR fixes it to return:

    "datasets": [
        {"request": "community/blab/ebola-narrative-ms@new-narrative",
         "buildUrl": "https://github.com/blab/ebola-narrative-ms"

This is probably a separate issue, but might as well mention it here: should `buildUrl` reflect the branch as well? For example:

    "datasets": [
        {"request": "community/blab/ebola-narrative-ms@new-narrative",
         "buildUrl": "https://github.com/blab/ebola-narrative-ms/tree/new-narrative"
