### ISSUE TITLE
Nextstrain gatsby section is missing a 404 page

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#123]
When we upgraded to gatsby v2 recently, we lost our 404 page!

To test -- https://nextstrain.org/doesNotExist goes straight to https://nextstrain.org/ and there is no 404 message shown. The original code 404 page [is here](https://github.com/nextstrain/nextstrain.org/blob/master/static-site/src/pages/404.jsx).

**Comment by bruminauta** [comment]
Hello, it seems to be working in local after building the app.

**Comment by jameshadfield** [comment]
Interesting -- not for me. Could you post a screenshot?

**Comment by jameshadfield** [comment]
Update via twitter - the 404 page works when using `gatsby serve` from within the static-site dir but not via `node server.js` which is how we run nextstrain.org.
