### ISSUE TITLE
[BUG] Hyphens in SARS-CoV-2 help page titles are replaced by spaces in the sidebar nav

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#137]
**Current Behavior**  
![image](https://user-images.githubusercontent.com/79913/77577230-a1155880-6e93-11ea-9b45-8ddbab270d78.png)

**Expected behavior**  
The hyphens are preserved.

**How to reproduce**  
Open https://nextstrain.org/help

**Possible solution**  
Adjust replacement pattern in whatever is currently converting hyphens in titles/filenames to spaces. I expect this is in our Gatsby customizations…

**Comment by chrisq21** [comment]
Hey @tsibley, I can look into this issue if you're not already working on it 👍

**Comment by tsibley** [comment]
@chrisq21 I'm not working on it, please do take it if you'd like. :pray: Thank you!

**Comment by tsibley** [comment]
(I assigned you since I'm not sure if you can assign yourself or not, but if you want to be unassigned, just let me know.)

**Comment by chrisq21** [comment]
No problem, taking a look!

**Comment by chrisq21** [comment]
Unassigned myself since @wlaurance seems to have a good solution in his PR
