### ISSUE TITLE
Zika Tutorial Instructions are for `augur` v1

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/nextstrain.org#146]
A contributor trying to get set up using the Zika tutorial pointed out that the `export` instructions in the tutorial didn't work - because they don't specify `export v1` or `export v2`

https://nextstrain.org/docs/tutorials/zika (bottom of page)

At the very least, these should be updated so that they work with the command `export v1` . Ideally, they should be updated to be `export v2` compatible! (Along with any other changes needed in `auspice_config.json` , etc).

**Comment by huddlej** [comment]
Thanks, @emmahodcroft! We actually have the same issue open already (#83)  with a little discussion about how to best address this. I'm going to close this as a duplicate and make sure the original issue is present on a project board. Let me know if you think this issue should remain open still though and we can reopen it.

**Comment by emmahodcroft** [comment]
Ah thanks!! No, no need to re-open. Might want to prioritise this though if possible, given the traffic - at least just add `v1` to the markdown (short-term fix). If I could remember how in the world to update Nextstrain.org docs I'd do this...
