### ISSUE TITLE
Charon does not support conditional requests

### ISSUE THREAD

**Issue by salvatore-fxpig** [nextstrain/nextstrain.org#150]
**Current Behavior**  
When requesting the getDataset? endpoint from a browser with cache, with the headers loaded `If-None-Match` and `If-Modified-Since` both loaded, the CloudFront server responds with a 200 (and possibly connects to origin to grab the data), the proceed to return the same ETag and `Last-Modified-Since` is equal to `If-Modified-Since` in the request.
This may induce additional loading times and significant additional strain on server if the requests are being routed to the origin.

**Expected behavior**  
The server should return 304

**How to reproduce**  
*From browser*:
Open network tab
Open https://nextstrain.org/ncov/global
Refresh repeatedly and observe the network request being carried out fully every time (no disk cache or memory cache are used)

*From command line*:
Run
```
curl 'https://nextstrain.org/charon/getDataset?prefix=/ncov/global' -H 'If-None-Match: "15dae69c5485864e77e2eca2bcc1d139"' -H 'If-Modified-Since: Thu, 16 Apr 2020 03:08:51 GMT' --compressed -v > dump
```
Substitute values of `If-None-Match` and `If-Modified-Since` for the most recent `ETag` and `Last-Modified` as obtained by response headers.
Example output:
```
> If-None-Match: "15dae69c5485864e77e2eca2bcc1d139"
> If-Modified-Since: Thu, 16 Apr 2020 03:08:51 GMT
>
{ [5 bytes data]
< HTTP/1.1 200 OK
< Connection: keep-alive
< X-Powered-By: Express
< Content-Type: application/json
< Content-Length: 1191430
< Date: Thu, 16 Apr 2020 03:09:32 GMT
< Content-Encoding: gzip
< Last-Modified: Thu, 16 Apr 2020 03:08:51 GMT
< X-Amz-Version-Id: dH9GQzvoJifVDaYofZIoU5C74rnIKlTE
< Etag: "15dae69c5485864e77e2eca2bcc1d139"
```
both the ETag and date match, but 200 is returned (304 would be expected)

**Possible solution**  
Possibly related to https://stackoverflow.com/questions/23222430/amazon-cloudfront-not-consistently-returning-304-not-modified-for-unchanged-st

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Linux, Windows
 - User agents:  Chrome, cUrl

**Additional context**  
This may induce additional loading times and significant additional strain on server.

**Comment by tsibley** [comment]
@salvatore-fxpig Thanks for this detailed report. Requests to `/charon` go through the API server in this repo. That API server proxies requests to CloudFront. Sometimes it can pass a CloudFront response through straight to the browser, other times it needs to transform it first before returning to the browser.

I don't think the API server can just naively pass along any conditional request headers like If-Modified-Since and If-None-Match to CloudFront, as it needs the content sometimes. There is an open PR #141 to add a caching layer to the API server—this implements conditional requests from the API server→ CloudFront—which might then also help with some of the infrastructure needed to support conditional requests from the browser → API server.

**Comment by salvatore-fxpig** [comment]
Hi @tsibley , thanks for the in-depth explanation, my initial understanding was that you had a CloudFront server sitting in front of the website, and not the other way around, i.e. proxying the CloudFront server (presumably serving S3 files?).

I didn't analyze this in-depth but it seems to me that there's at least one big path where the request is proxied transparently to CloudFront using request.pipe(), and the server does not touch it at all.

In this case it may make sense to have a full proxy, that which can be achieved with a very minor modification, that should be completely harmless; https://github.com/nextstrain/nextstrain.org/pull/161

This is a bit orthogonal to PR #141 as far as I can see but not quite sure how the two would play together ATM.

**Comment by salvatore-fxpig** [comment]
Doing this with `fetch` turns out to be absolutely non-trivial, nonetheless after some hours of banging my head against a wall I managed to cook up this PR: #162

**Comment by tsibley** [comment]
Thanks for all the looking into this you did, @salvatore-fxpig. This issue will be resolved by https://github.com/nextstrain/nextstrain.org/pull/557, which switches the Charon API endpoints to use some more systematic and comprehensive caching and conditional request handling in [new code paths](https://github.com/nextstrain/nextstrain.org/blob/ee0c3f3ddc12fc231c27d0e93865d49246f3e8f2/src/endpoints/sources.js#L488-L544) that I wrote for other endpoints in the meantime.
