### ISSUE TITLE
You're already being used to justify conspiracy theories: please don't

### ISSUE THREAD

**Issue by davecb** [nextstrain/nextstrain.org#152]
For example, here's a claim that a vaccine is impossible, based on your work:
https://www.facebook.com/photo.php?fbid=10159242915813594&set=a.10150512374863594&type=3&theater

Your results are meaningful and helpful to people working in the space, but unless you can communicate the implications of your work in a single paragraph, an "elevator pitch", you're going to be used to start new conspiracy theories.

You have good supporting information, but your readers are people like me, a logician, not a doctor. If you don't say exactly what the implications are in the first paragraph of your pages, you  _will_ be used by the evil and the paranoid to 'sell" the exact opposite of the truth.

Feel free to contact me, or someone in science communication

--dave
davecb@spamcop.net

**Comment by colinmegill** [comment]
Counterexample https://twitter.com/LeiaRx/status/1252937548625829888

**Comment by colinmegill** [comment]
@sidneymbell there are a handful of major questions/misperceptions answered by a handful of major threads by @trvrb ... perhaps helpful to aggregate those threads / blogposts as an FAQ and linkout from a more visible place in the interface and narratives, if not already sufficiently covered?

**Comment by trvrb** [comment]
I think linking out to rebuttals of prominent misconceptions would be good. I've aggregated threads here: https://bedford.io/misc/twitter/
