### ISSUE TITLE
Show previous COVID-19 situation reports on Nextstrain website

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/nextstrain.org#153]
**Context**  
Now that we're publishing situation reports focused on specific regions, accessing previous reports would be really useful. For example, the North American reports are not updated every week. But if I want to read the most recent analysis on North America, I need to be able to navigate to a previous week's report. From the splash page, readers cannot do that. Instead, they have to know the URL of the report they want to read.  

**Description**   
From the splash page, I'd like to add a link to another web page showing previous situation reports with their translations. Because of the sheer number of these reports, this might be best done with a click and scroll box for date and a click and scroll box for language. Choosing a report by topic rather than date would also be a useful feature.

**Comment by jameshadfield** [comment]
👍 this is important. I can try to set up the beginnings of a static page within Gatsby today to show these and perhaps @eharkins can work on this (or @eharkins can start the page if I don't get to it!)

**Comment by cassiawag** [comment]
Thanks @jameshadfield & @eharkins!
