### ISSUE TITLE
add instructions on how to generate the splash page tiles

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#18]

**Comment by jameshadfield** [comment]
Notes here (todo: move to docs):

lunapic -> upload picture -> "art" menu -> "grey" for our cards, "floating" for community cards -> adjust slider as you see fit -> crop (simple crop tool with square selected) -> resize to ~ 250 x 250px -> save as png

Don't forget to add the credit to `SplashImagesCredit` in `Footer/index.jsx`.

**Comment by tsibley** [comment]
Thanks!
