### ISSUE TITLE
SARS-CoV-2 tools

### ISSUE THREAD

**Issue by rneher** [nextstrain/nextstrain.org#182]
There is a growing need for people to assign their sequences to clades and do some simple QC. In the longer term, we also want to support running augur on SARS-CoV-2 data in the cloud. I imagine a collection of tools that grows over time, but there are two distinct categories:

1) full builds that are run in the cloud with the results hosted permanently. This probably wants to be integrated with groups and requires more infrastructure

2) simple tools that run on the client like clade assignment, QC (mutations relative to reference etc). We have one prototype of such a tool at https://github.com/neherlab/webclades

We are planning to have a site that lists all SARS-CoV-2 builds (https://github.com/nextstrain/nextstrain.org/issues/180). This Issue is meant to start a discussion of how to make builds and tools as discoverable as possible.

**Comment by jameshadfield** [comment]
My idea (not particularly innovative) would be to transform https://nextstrain.org/sars-cov-2/ into a general landing page for all things SARS-CoV-2. This would include (either within the page, or via links)

* General introduction
* https://clades.nextstrain.org/
* List of all SARS-CoV-2 datasets that we are aware of (what's currently on https://nextstrain.org/sars-cov-2/). We talked previously about making a geo-based viz for this to better convey the coverage of builds.
* List of situation reports (https://nextstrain.org/ncov-sit-reps)
* Link to tutorial to run your own build https://nextstrain.github.io/ncov/

**Comment by emmahodcroft** [comment]
I like James' idea above 👍

**Comment by eharkins** [comment]
First version of this was done in https://github.com/nextstrain/nextstrain.org/pull/206 and can be seen at https://nextstrain.org/sars-cov-2/. Today on a call we talked about some improvements, here are some notes / proposals from the meeting notes:

> 1. Can we make it so that people can update their build inclusion in our ‘list’ via a PR somehow?
> 2. Can we get some easy wins initially by some visual adjustments to our current list - 2 columns, smaller gaps, smarter wrapping?
> 3. Long term - can we make it more generic that can be used for any Nextstrain builds lists. Should it be searchable? Map? Images? 
> 4. Can we move things like the search database updates to Github Actions so that they’re easier to run (either Build Shepherds or scheduled) once a month or so, and keep up to date?

I can help make simple UI improvements right now (number 2) if we are clear on how we want this to look.

**Comment by trvrb** [comment]
I believe this issue can be closed. Nextclade is launched and `/sars-cov-2` is a landing page. There is perhaps more work to be done, but I wouldn't tie it to this issue.
