### ISSUE TITLE
Document Nextstrain groups

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/nextstrain.org#184]
Per @trvrb, nextstrain.org/groups should give a one paragraph overview of the future and then list all the public groups. 

There should be separate documentation in nextstrain.org/docs that covers things in detail for users 

Further context visible at [this Slack thread](https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1592425359105100).

**Comment by jameshadfield** [comment]
👍  Currently [this](https://nextstrain.org/docs/contributing/sharing-data#nextrain-groups) is the extent of the groups-related docs on nextstrain.org. https://github.com/nextstrain/cli/issues/90 is also relevant here. 

Note that all public groups are listed on the splash page _if_ you have a login!

**Comment by tsibley** [comment]
> Note that all public groups are listed on the splash page _if_ you have a login!

Yeah, surfacing of those is currently pretty weird and confusing! :upside_down_face: Especially since public groups you've never heard of are mixed in with your private groups.

**Comment by joverlee521** [comment]
In PR #193, a separate docs page for Nextstrain Groups was started: 
https://nextstrain.org/docs/contributing/nextstrain-groups

**Comment by genehack** [comment]
From looking at https://nextstrain.org/groups/ I think the intent of this issue has been achieved, and so I'm going to close it out. If there's remaining stuff to do, please re-open with a description of what that work should be.
