### ISSUE TITLE
Unable to load JSONs not in the manifest

### ISSUE THREAD

**Issue by trvrb** [nextstrain/nextstrain.org#20]
@jameshadfield ---

Previous to PR #8, it was possible to push something to staging and not update the manifest and still be able to load the JSONs by typing in URL directly. After PR #8, all JSONs need to be represented in manifest. I believe the former is more optimal behavior. Nice to be able to easily share obscured results through staging server.

You can see this behavior in the following:

* Staging JSONs exist here: http://staging.nextstrain.org/dms_flu_seasonal_h3n2_ha_2y_meta.json, http://staging.nextstrain.org/dms_flu_seasonal_h3n2_ha_2y_tree.json
* JSONs don't load into auspice here: https://nextstrain.org/staging/dms/flu/seasonal/h3n2/ha/2y

**Comment by jameshadfield** [comment]
@trvrb as a stopgap can we either (a) revert https://github.com/nextstrain/nextstrain.org/commit/f616c65e42ed1b6445bb2065725da7f97420a688 or (b) add the dms data to the staging manifest. I'll try to get onto this in the next two days, but if I don't get around to it this week it'll have to be after HK
