### ISSUE TITLE
community builds hosted on github lfs do not work

### ISSUE THREAD

**Issue by ttung** [nextstrain/nextstrain.org#213]
**Current Behavior**  
`https://raw.githubusercontent.com/<ORG>/<REPO>/<BRANCH>/auspice/<DATASET>.json` (the [default place](https://github.com/nextstrain/nextstrain.org/blob/master/src/sources.js#L165) where the data is being pulled from for github repos) will serve a LFS pointer.  `https://github.com/<ORG>/<REPO>/raw/<BRANCH>/auspice/<DATASET>.json` will serve the data, but incurs an additional 302 request.

As a result https://nextstrain.org/community/czbiohub/covidtracker/ca is currently broken.

Example: 

https://raw.githubusercontent.com/czbiohub/covidtracker/master/auspice/covidtracker_ca.json produces a LFS pointer
https://github.com/czbiohub/covidtracker/raw/master/auspice/covidtracker_ca.json produces the right data after a 302 redirect.

**Comment by huddlej** [comment]
This issue was resolved by #215
