### ISSUE TITLE
The nextstrain.org server no longer needs to identify dataset requests for multiple trees

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#218]
The nextstrain.org server parses the dataset requests originating from the Auspice client largely within the `parsePrefix` function. This function contains logic for identifying single requests for multiple datasets (i.e. tangle-trees), which is an artifact from a time where the server would fetch all relevant JSONs and combine them server-side.

Auspice now always makes separate requests for each dataset. E.g. http://localhost:5000/ncov/global:ncov/oceania results in two GET requests, http://localhost:5000/charon/getDataset?prefix=ncov/oceania and http://localhost:5000/charon/getDataset?prefix=/ncov/oceania. 

As we move to simplify the `parsePrefix` function and delegate more responsibility to the `Source` class / subclasses, this should be removed.

(There are lots of little bits which are no longer accurate, such as `auspiceDisplayUrl` now being used as a redirect rather than handed to Auspice. I'm unsure whether to make individual issues for all of these.)

**Comment by tsibley** [comment]
Closed by #296.
