### ISSUE TITLE
Tree Data Downloaded from Website seems to Use Different Sample Identifiers.

### ISSUE THREAD

**Issue by daenuprobst** [nextstrain/nextstrain.org#241]
**Current Behavior** 
This happens when downloading the data sets from the (bottom of the) website:

The sample identifier (e.g. "Panama/330671/2020") from `nextstrain_ncov_metadata.tsv` does map to `nextstrain_ncov_global_timetree.nwk` but not to `nextstrain_ncov_global_tree.nwk`.

**Expected behavior**  

The sample identifier (e.g. "Panama/330671/2020") from `nextstrain_ncov_metadata.tsv` should map to both `nextstrain_ncov_global_timetree.nwk` but not to `nextstrain_ncov_global_tree.nwk`.

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Download `nextstrain_ncov_metadata.tsv`, `nextstrain_ncov_global_timetree.nwk`, and `nextstrain_ncov_global_tree.nwk` from website.
2.  Compare the node names / identifiers in the nwk files to the sample identifier in the metadata file.
3. `nextstrain_ncov_metadata.tsv` **can** be mapped to `nextstrain_ncov_global_timetree.nwk`
4. `nextstrain_ncov_metadata.tsv` **cannot** be mapped to `nextstrain_ncov_global_tree.nwk`

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Ubuntu 20.10
 - Browser:  Edge (Linux beta)

**Comment by jameshadfield** [comment]
Hi @daenuprobst -- I just tried to reproduce this by going to https://nextstrain.org/ncov/global and using the "download data" functionality to download the "tree", "timetree" and "all metadata" files. `"Panama/330671/2020"` appears in all three for me. Note that in your issue you mention  `Nextstrain_ncov_metadata.tsv` whereas the downloaded filename is actually `nextstrain_ncov_global_metadata.tsv`. Please reopen if you are still having trouble here.
