### ISSUE TITLE
Bosnia-Herzegovina build is listed within Auspice and on website but does not exist

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextstrain.org#251]
**Current Behavior**  
Bosnia(-Herzegovina) build is listed and selectable, but does in fact not exist

**Expected behavior**  
Either correct build is linked or mention of Bosnia is removed from website and auspice. 

**How to reproduce**  
For website, reproduction is along the lines of https://github.com/nextstrain/nextstrain.org/issues/249 just with Bosnia-Herzegovina instead of Czechia

For reproduction within Auspice, open e.g. this link: https://nextstrain.org/groups/neherlab/ncov/bulgaria?c=clade_membership&f_country=Bulgaria&p=grid&r=division then select `bosnia` from dropdown.

**Environment**
Live build as of 7.20pm (German time) on 10 Jan 2021 using Brave (Chromium)

![image](https://user-images.githubusercontent.com/25161793/104131789-054cce80-5379-11eb-923e-5b4726df6d71.png)

**Comment by rneher** [comment]
Thanks for flagging this! This is the result of the build being named `bosnia_and_herzegovina` when it should use hyphens. I have fixed this on the data-set side. Still need to update the link in analogy to:

https://github.com/nextstrain/nextstrain.org/pull/250
