### ISSUE TITLE
Bosnia is shown in Auspice in addition to Bosnia-Herzegovina

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextstrain.org#254]
Seems to be incomplete fix of #250 

Bosnia is still showing in addition to Bosnia-Herzegovina

![image](https://user-images.githubusercontent.com/25161793/104164312-0709a700-53f8-11eb-9911-4dad88a745d9.png)

**Comment by rneher** [comment]
thanks! There was one additional file in the bucket with the wrong naming convention. it should now be gone.

**Comment by jameshadfield** [comment]
Can confirm that the Bosnia build has now been removed & no longer appears in the dropdown. Thanks both!
