### ISSUE TITLE
Improve UI: sequence search results for community datasets

### ISSUE THREAD

**Issue by eharkins** [nextstrain/nextstrain.org#270]
#266 allows datasets in the [sars-cov-2 build catalogue](https://github.com/nextstrain/nextstrain.org/blob/master/static-site/content/allSARS-CoV-2Builds.yaml) to be included in the sequence -> dataset search results available at https://nextstrain.org/search/sars-cov-2/. We'd like to improve how those datasets appear in search results on that page in the following ways:

- change the [file icon displayed next to the dataset](https://github.com/nextstrain/nextstrain.org/blob/master/static-site/src/pages/sequence-search.jsx#L198) to match [those used on the build map component](https://github.com/nextstrain/nextstrain.org/blob/master/static-site/src/components/sars-cov-2/build-map.jsx#L121) (according to the geographic level of the build). See https://github.com/nextstrain/nextstrain.org/pull/266#issuecomment-772175894 for generally how this would work.
- cleaning up the displayed URL in search so that we don't display the query part. This should be a more simple addition of some logic to the [code that parses the dataset filename and displays it as a URL](https://github.com/nextstrain/nextstrain.org/blob/master/static-site/src/pages/sequence-search.jsx#L199).

**Comment by eharkins** [comment]
It also might be good to update language on the search page to inform folks who arrive at that page (not necessarily from the main sars-cov-2 resources page which has its own language about the search feature) what the requirement is for a dataset to be included in the search results. Or just make existing language describing the data behind the page more accurate.

The current language is:
> _Search all SARS-CoV-2 nextstrain builds, including historical ones, for particular strain name(s)_

(on https://nextstrain.org/sars-cov-2)
and:
> Current database: 28136 samples, from 312 datasets on the core nextstrain bucket

(on https://nextstrain.org/search/sars-cov-2)

The parts of this I would say (after #266) are no longer completely accurate are  
> nextstrain builds

assuming this means build by the Nextstrain team - maybe it just means build created with Nextstrain software.

and 
> datasets on the core nextstrain bucket

since this isn't true of all builds in the catalogue.

**Comment by genehack** [comment]
This issue has been sitting untouched for over three years. The links to the source code that need to change are no longer in the repo, and the `/search/sars-cov-2` page is gone. We’re trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on, so I'm going to go ahead and close it out. 

If you think this issue reflects an ongoing issue or other work that still should be a priority to accomplish, please re-open the issue and explain why.
