### ISSUE TITLE
/users/:name endpoint always responds with current user's information

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#294]
**Current Behavior**
The `/users/:name` endpoint responds with the current user's information to any request under `/users/**`. For example, you can visit https://nextstrain.org/users/hello/world/how/are/you.

**Expected behavior**  
`/users/:name` only works for the currently logged in username.

In the future, `/users/:name` may return a user's public profile for any valid user, but that is a separate concern.

**Comment by jameshadfield** [comment]
Quick note on the code which is causing this, in the hope that it will help someone with the fix.

Our server will send URLs such as these a gatsby-build HTML file. Confusingly (to me, at least) it doesn't actually matter which page the server sends, so in current master 363209e a `/users/a` URL will get sent  `static-site/public/404.html`, as no matching static page exists in the `/static-site/public` directory. 

Gatsby is configured using
```js
        createPage({
          path: "/users",
          matchPath: "/users/*",
          component: path.resolve("src/sections/users.jsx")
        });
```
and so Gatsby's client routing will mean any URL starting with `/users` will end up rendered by `src/sections/users.jsx`. This routing will be triggered from any gatsby-built HTML, which in this case is actually the 404 page!

The page in `src/sections/users.jsx` relies on the users cookie (via a `/whoami` API call) to determine the user. It never inspects the URL.
