### ISSUE TITLE
404 issues

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#3]
### These URLs should 404 but result in a crash
* https://nextstrain.org/local
* https://nextstrain.org/docs/ds

Furthermore, the 404 message should be improved. If Auspice also had a 404 page (at, `/404`) then we could redirect urls such as https://nextstrain.org/influenza there, so that for nextstrain.org a unified 404 page is used.

Most of these are issues to be resolved in the static repo. Some are in auspice.

**Comment by kairstenfay** [comment]
> ### These URLs should 404 but result in a crash
> 
>     * https://nextstrain.org/local
> 
>     * https://nextstrain.org/docs/ds

They 404 for me :)
