### ISSUE TITLE
Mocks for pages listing shared datsets & narratives

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#305]
Recent work (including #287 #299 #201 #302) now makes it feasible to create pages listing datasets & narratives shared through nextstrain.org via methods such as community, groups etc. This issue focuses on mocks for the frontend work. Here I don’t consider the problem of collecting this data and keeping it in sync, this issue presumes that such a file is able to be fetched by the client. I also assume that such a file does not include parsing of the dataset file itself, which limits the metadata we are aware of for a given dataset / narrative. 

For most of the sources I believe we can use a single template page, with different content (both text & fetched data file). These would be sourced from the following pages:
* `/pathogens` (`/core` would redirect here) - representing our core datasets. Table columns would be dataset & date updated.
* `/staging` Same table columns as above.
* `/groups` Private groups should also be shown, implying that the datasets must be dynamically generated by our server. Table columns: “Dataset”, “date updated”, “Group name”.
* `/community` Consideration should be taken on whether all datasets are shown, or whether people can opt-out. Table columns: “Dataset”, “date updated”, “GitHub organisation”.

![image](https://user-images.githubusercontent.com/8350992/114330937-f43d7480-9b96-11eb-9a5a-18acb612d57e.png)

We may also wish to have an `/sharing` page, which fetches data from all the above sources. Such a page would imply the others have been implemented!

* `/fetch` would work somewhat differently, but it would be nice to surface a page for this functionality.

![image](https://user-images.githubusercontent.com/8350992/114330940-f8699200-9b96-11eb-9ed1-0dbc17a62414.png)

**Comment by jameshadfield** [comment]
@eharkins's issue #343 on how to surface groups from the nextstrain.org frontpage made me revisit this issue. In general, I think we need a small set (6 or so) of components that we can reuse across all of the pages we are now creating (/groups, /community etc). These components will handle the styling, so that page authors can focus on the content rather than the aesthetics. It also provides continuity across the site.

**Six reusable components that will allow the functionality we want for _most_ pages**

(Colours here identify the components, I'm not proposing we make each component a different colour 😂 )

![image](https://user-images.githubusercontent.com/8350992/120091897-2a44b100-c163-11eb-82ba-c26e23dffb41.png)

**How a selection of pages would look*

One benefit is that the source code for each of these pages would now have a much higher ratio of content to styling. Right now the two are very intertwined.

![image](https://user-images.githubusercontent.com/8350992/120091909-48aaac80-c163-11eb-8ff0-2b5a886c2f0a.png)

![image](https://user-images.githubusercontent.com/8350992/120091912-4e07f700-c163-11eb-81e7-000aea658963.png)

![image](https://user-images.githubusercontent.com/8350992/120091915-53654180-c163-11eb-887a-d048be49d9b0.png)

![image](https://user-images.githubusercontent.com/8350992/120091932-83ace000-c163-11eb-8b23-ccc4763dcf2e.png)

**Comment by genehack** [comment]
I believe this work has largely all been implemented; closing this issue out.
