### ISSUE TITLE
Link target openscienceprize.org no longer online, replace with archive.org link?

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextstrain.org#329]
**Current Behavior**  
The website linked to in the footer for the [Open Science Prize](openscienceprize.org) seems to be no longer online.

**Expected behavior**  
Open Science Prize website shows

**How to reproduce**  
1. Open https://nextstrain.org/
2. Scroll to the bottom
3. Click on the Open Science Prize logo

**Possible solution**  
Replace with archive.org link https://web.archive.org/web/20210318234028/https://www.openscienceprize.org/

**Additional Context**
Same website is also linked to from the footer of the docs

**Comment by trvrb** [comment]
Thanks for the catch @corneliusroemer. I appreciate you letting us know. A quick google suggests that we should update to https://www.nih.gov/news-events/news-releases/open-science-prize-announces-epidemic-tracking-tool-grand-prize-winner

@eharkins: Would you be able to make this update?

**Comment by corneliusroemer** [comment]
Yes, that's maybe cleaner.

These are all the locations where the URL appears within the nextstrain organization:
https://github.com/search?q=org%3Anextstrain+openscienceprize.org&type=code

**Comment by eharkins** [comment]
Thank you @corneliusroemer! Fixed in e842ac3e8c4b0a43b8e66bce6e0fb0b98b9a36cb. 

I will also release a new version of https://github.com/nextstrain/sphinx-theme so that docs.nextstrain.org gets the fix. 

https://github.com/nextstrain/static appears to be deprecated.

@trvrb should I also update https://github.com/nextstrain/sandbox?

**Comment by jameshadfield** [comment]
I don't know what https://github.com/nextstrain/sandbox is, although it's only me who's committed to it! Am going to archive it now.
