### ISSUE TITLE
Improve server error logging

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#330]
Improvements in our server handling (e.g. #320, #327) have moved us in a direction where we throw suitable errors to be caught by express' default error handling layer. Each time such an error is caught, for instance when a dataset is not found, the server logs the stack trace such as:

![image](https://user-images.githubusercontent.com/8350992/118756084-41abb080-b8be-11eb-8390-266feb3c26b2.png)

This happens irregardless of what NODE_ENV is set to. (The response content the client receives _does_ change according to this variable, but not the server logging.)

We should only print stack traces if specifically requested, e.g. via a command line arg, as most of the time when developing these traces are more hindrance than help.

**Comment by jesum44** [comment]
Hey @jameshadfield, we are starting to work on this issue and wondering if you could answer a few questions.

We are trying to recreate the server logs that you showed in the example, but are unsure on where to find them. Is there a log file that shows all the logs, or do we need to have server access and the logs will just show up on the console?

Also, should there be a separate command line argument that specifies whether devs should show the server error logging or should we include the functionality as part of the Verbose command line argument that already exists?
Thanks!

**Comment by jameshadfield** [comment]
Hey @jesum44 

> We are trying to recreate the server logs that you showed in the example, but are unsure on where to find them. 

They are printed into your terminal whenever you run the server locally. They won't have identical formatting as the above screenshot, but that doesn't matter. This issue is around [node's development vs production mode](https://nodejs.dev/learn/nodejs-the-difference-between-development-and-production), so the two incantations are:
```sh
NODE_ENV="dev" npm run server --verbose # don't technically need to set NODE_ENV here, but it's clearer
NODE_ENV="production" npm run server --verbose
```
Note that to run in production mode locally you'll have to comment out / remove [this line](https://github.com/nextstrain/nextstrain.org/blob/master/src/app.js#L60) so that the server doesn't try to use https on localhost. 

> should there be a separate command line argument that specifies whether devs should show the server error logging

If `NODE_ENV="production"` then the stack traces should not be shown. Whether they should be toggle-able in "dev" mode is a separate issue, and can be addressed once this is sorted.

Thanks in advance!
james

**Comment by tsibley** [comment]
FWIW, I think this is likely to be subsumed by bigger improvements proposed in https://github.com/nextstrain/nextstrain.org/issues/511 instead.

**Comment by genehack** [comment]
Closing this older issue out in favor of the aforementioned #511.
