### ISSUE TITLE
404-page flashes during login / logout

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#34]
There are weird double page loads or redirects happening when navigating across the boundary between Auspice and nextstrain.org. For example, go to https://nextstrain.org/zika, click Docs in the nav, observe a flash of the home page before the doc page loads. There are other navigation flows where this happens as well. This seems to be the fault of the gatsby-plugin-catch-links plugin, which installs a global onclick handler that tries to be smart but is in fact dumb.

**Comment by jameshadfield** [comment]
> click Docs in the nav, observe a flash of the home page before the doc page loads

Also happens if you simply navigate to nextstrain.org/docs -- would be great to get rid of this!

**Comment by kairstenfay** [comment]
I see a "404" page flicker when I click "Login".

**Comment by jameshadfield** [comment]
After the progress made in #71 I believe this now only happens with 404 pages and login/logout.

![login404](https://user-images.githubusercontent.com/8350992/71954520-762f4700-324a-11ea-9e9c-a54a406180bb.gif)
![logout404](https://user-images.githubusercontent.com/8350992/71954521-762f4700-324a-11ea-826d-b96de1b120ae.gif)

**Comment by jameshadfield** [comment]
This is fixed by https://github.com/nextstrain/nextstrain.org/pull/75, but there may be other regressions introduced there.
