### ISSUE TITLE
Stochastic CI build failures

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#340]
Noticed by @eharkins at https://github.com/nextstrain/nextstrain.org/pull/336#issuecomment-849088453

[This is the failing TravisCI build](https://travis-ci.com/github/nextstrain/nextstrain.org/builds/226854996#L831). A force-push triggered another CI run which passed. 

```
   ✕ Check that getAvailable API call for a non-existent community source 404s (50 ms)
...
  ● smoke testing URLs described in urls.json › Check that getAvailable API call for a non-existent community source 404s

    expect(received).toEqual(expected) // deep equality
    Expected: 404
    Received: 200
```

I haven't looked into this, but a failure where it returns `200` is rather strange. Note that failing CI runs will prevent automatic deploys, so this should be explored ASAP. @eharkins could you take a look?

**Comment by eharkins** [comment]
Possibly another example here https://app.travis-ci.com/github/nextstrain/nextstrain.org/builds/232095890#L826.

**Comment by tsibley** [comment]
Closing as outdated now, several months later. CI's been largely ok, but if we run into persistent CI issues again, we'll notice and can investigate then.
