### ISSUE TITLE
Missing resource banner UI

### ISSUE THREAD

**Issue by eharkins** [nextstrain/nextstrain.org#342]
Currently on https://nextstrain.org/, when requesting a url like https://dev.nextstrain.org/groups/seattleflu/test, i.e. one that looks like an auspice dataset but where the dataset doesn't exist, we show a banner in letting you know that the dataset doesn't exist and fall back to a page (rendered by Auspice) listing the group datasets if the group exists. 

On https://dev.nextstrain.org/, i.e. #341, we instead serve (from Gatsby) a page for the appropriate group if the group exists, listing valid datasets and narratives for that group. We also show a banner with a similar message, but the design of that banner could be improved. This issue is to solicit feedback on the UI/design of this "missing dataset" banner.

#339 is a first attempt at a design of this banner using the full-page-width style similar to auspice, but with a more subtle color. Feedback on that design or other proposals / mock-ups here would be appreciated!

**Comment by jameshadfield** [comment]
(See #305 for one potential UI design)

**Comment by genehack** [comment]
This fallback behavior is currently active on nextstrain.org, so I'm going to close this issue out.
