### ISSUE TITLE
Navigate from nextstrain.org to nextstrain.org/groups

### ISSUE THREAD

**Issue by eharkins** [nextstrain/nextstrain.org#343]
In the next release (#341) we add a page, https://dev.nextstrain.org/groups/, which summarizes the Nextstrain Groups feature and lists datasets and narratives for all groups visible to the user. 

This issue is to solicit feedback on some proposed ways to make the above mentioned page easy to find by navigating to it from the splash page. Any additional UI proposals are welcome and appreciated!

### Design 1:
- Removes the groups cards (normally displayed only for a logged in user; part of the goal with the `/groups` page is to make Nextstrain Groups something that isn't only visible to logged in users).
-  Button labeled "More on Nextstrain Groups" that links to `/groups`.
-  Additional sentence explaining about where the button is taking you.
<img width="852" alt="Screen Shot 2021-05-27 at 1 43 38 PM" src="https://user-images.githubusercontent.com/12140437/120028992-79ec7680-bfc3-11eb-8738-6536d091d73b.png">

### Design 2:
- Leaves out the extra sentence from Design 1.
- Button from Design 1.
- Groups cards
<img width="972" alt="Screen Shot 2021-05-27 at 1 53 17 PM" src="https://user-images.githubusercontent.com/12140437/120028994-7a850d00-bfc3-11eb-9cfe-68f0e6da33aa.png">

I prefer Design 1 since the groups cards are also shown on `/groups` I was thinking of `/groups` as replacing the groups section on the splash page. The potential downside of this is that it relies on those two sentences to pique one's interest enough to click on the button. Maybe there's some middle ground solution that lists only a few groups and so saves space / reduces redundant listing of groups. But this may not be necessary if we are confident the paragraph/button suffice as a way to get people over to /groups who don' already know about it.

**Comment by trvrb** [comment]
I'll think more on this, but relatedly:

I think that all groups that a logged in user belongs to should be surfaced as tiles on the homepage. It's super common that users that belong to groups will want to jump to the relevant groups page.

These quick access tiles could be completely invisible to users who are not logged in.

**Comment by eharkins** [comment]
That makes sense to me; giving folks shortcuts if they already are signed up for groups.

**Comment by jameshadfield** [comment]
Thanks for starting this discussion @eharkins! I made a number of mocks on #305 which propose one solution to this issue.

**Comment by genehack** [comment]
The front page of Nextstrain.org links to the groups page now, so I'm going to close this issue out.
