### ISSUE TITLE
When loading group pages, "no datasets available" displayed for 0.5s

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextstrain.org#353]
*Low severity*
**Current Behavior**  
When loading a group page like https://nextstrain.org/groups/swiss/ the first render (after ca. 300ms) contains the incorrect statement *Available dataset: None found* which then gets replaced by the correct page only after 500ms.

**Expected behavior**  
If a dataset is available, the user does not get told that there is no available dataset, even for only 500ms

**Possible solution**  
Show a spinner, while data is awaited or show `None found` only after 1-2s after page load, leaving a white page till then.

**Screenshots of render sequence with timestamps**
![image](https://user-images.githubusercontent.com/25161793/122589436-8b73ec00-d060-11eb-9a0c-03330b98c75c.png)

**Comment by jameshadfield** [comment]
Closing this as recent PRs have completely changed how these splash pages render so that we now have a "Data loading" page replaced by the final version. Spinners (#304) would make things even better!
