### ISSUE TITLE
Redesign splash page to highlight other pages

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#388]
**Context**  
The [nextstrain.org](https://nextstrain.org) landing (splash) page consists of a number of sections highlighting different data collections: groups, sars-cov-2, (core) pathogens, community, narratives. Note that "groups" were only displayed when a user was logged in, despite the presence of public groups. 

We now have specific pages for all of these sections except narratives:
- https://nextstrain.org/groups/ (which works for non-authenticated users as well)
- https://nextstrain.org/sars-cov-2/
- https://nextstrain.org/pathogens
- https://nextstrain.org/community/

Those individual pages typically contain more complete data listings than those on the splash page, which was designed in a time when far fewer datasets were shared through nextstrain. Furthermore, there are no links from the splash page to these pages. 

**Description** 

Redesign the splash page to reduce the content in each section and pointing to the respective page. Using similar mocks to #305:

![image](https://user-images.githubusercontent.com/8350992/126939080-88ea238e-2094-4c17-a596-c59f49920f09.png)

- Similar to the layout of the "Philosophy" section, the sections should display as 2 columns when screen size allows. Breakpoints should be the same across these sections. 
- I think section abstracts should be centred, as they currently are (although the Philosophy section is left aligned).
- The number of cards displayed should be explored across different screen sizes. I think it's best to have only one row (maybe two rows on mobile view, or maybe no cards at all on mobile view). We will never provide an exhaustive listing of data with the cards as we once could, the idea is to direct users to the page for that section which does list everything.
    - There's plenty of things to explore with the display of cards - carousels, random selections, etc - but for expediency they should stay hardcoded.
- the Narrative "Find out more" button link is [to the docs](https://nextstrain.github.io/auspice/narratives/introduction)

**Examples**

#305 proposed a similar end result, but with a focus on reusable components. This issue focuses should be on the user-facing changes rather than component design, which can come later.

**Comment by trvrb** [comment]
I back this. I don't have major suggestions, but just a couple small thoughts:
1. I would like to keep an obviously clickable image to bring users directly to https://nextstrain.org/ncov/gisaid/global. Though this could easily be accomplished in above design with two tiles under SARS-CoV-2: one for `ncov/gisaid/global` and the other for `ncov/open/global` and otherwise people clicking on the "see all resources" text.
2. I think I remember the two column philosophy sections looked better as left-aligned, but we'd just have to play around here. Agree it should be consistent and center alignment could well work better given section tiles.

**Comment by jameshadfield** [comment]
:+1: let's add 2 tiles for nCoV (GISAID & open), and two tiles for groups (maybe SPHERES & neherlab, or seattleflu?) so that things are visually lined up.

**Comment by emmahodcroft** [comment]
I also think this is a great direction! I agree with Trevor that maybe a couple more tiles in the first section could let people get to some of the most interesting things, and useful examples, easily.

**Comment by jameshadfield** [comment]
Closed by #390
