### ISSUE TITLE
Nextstrain private

### ISSUE THREAD

**Issue by mabvakureb** [nextstrain/nextstrain.org#389]
Hi, maybe this has been asked before, is it possible to have a private nextstrain functionality similar to github private repositories. In the nextstrain private ones we could upload our nextstrain builds from our github private repositories and this would only be visible in our lab, or other labs that have permissions to login. This is for builds were the data cannot be shared to the public. 

**Alternative 2**
https://auspice.us/ is an alternative, I like to include it in rmarkdown for example to generate an html, by doing something like:

 [Pathogen xx1](https://auspice.us/ && link to my nextstrain auspice datasets xx1 on my private machine)
 [Pathogen xx2](https://auspice.us/ && link to my nextstrain auspice datasets xx2 on my private machine)

And running these as part of my rmarkdown would generate an html document which has links to automatically open my nextstrain builds with auspice.us?

**Comment by mabvakureb** [comment]
Or maybe instead of dragging and dropping by datasets into https://auspice.us/ can i write something after it in search tab pointing to the location of my files? I think it might be easier to code that way too

**Comment by jameshadfield** [comment]
Hi @mabvakureb - for private datasets shared through nextstrain.org, please see if [nextstrain groups](https://nextstrain.org/groups/) would be appropriate for your use case.

Auspice.us is unable to access local files via URLs / links, only via drag&drop. If you want to view local datasets you can install & run auspice locally, but that won't help with sharing those URLs.
