### ISSUE TITLE
Future organisation of nextstrain.org (request for comments)

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#4]
Right now this repo contains the server behind nextstrain.org, and serves pre-build html/js/css of the [static site](https://github.com/nextstrain/static) and auspice. It also imports some server funtionality from the auspice repo.

### Auspice
As the whitelabelled auspice gets rolled out, this changes things vastly for the better (I think).

The customised auspice client could be built within this repo by having auspice as a dependency and running `auspice build --extend ...` when we rebuild nextstrain.org.
This allows nextstrain to pin a version of auspice, and decouples auspice releases from nextstrain.org releases.

The code to handle requests from auspice (e.g. `charon/getDataset`), which used to live in the auspice repo, is now part of this repo (e.g. see [this file](https://github.com/nextstrain/nextstrain.org/blob/whitelabel/server.js#L71)). (Note that auspice itself only contains server code to deal with local datasets, so this isn't duplicated code. Utility functions / helpers could be imported via `import {x} from "auspice"` since auspice is a dependency already.)

All of this allows easy testing and development of (extended-)auspice within the nextstrain.org framework. (This is possible now but a bit clunky).

### Available datasets
Currently the splash page tiles are [hardcoded in the static website](https://github.com/nextstrain/static/blob/master/src/components/splash/cards.jsx). The available datasets given to auspice (auspice makes [this request](https://nextstrain.org/charon?request=available&url=/)) are derived from the "manifest_guest.json" which [is located on S3](http://data.nextstrain.org/manifest_guest.json). Further complicating things, those two links show that we're using different JSON formats!

With the auspice updates, the responsibility for processing the auspice request is all on this repo. Auspice will have a well defined file format it expects, but the way this server generates that is completely flexible.
This means:
* We could include the "manifest", or some listing of datasets within this repo. Updating the available datasets would then require pushing a new commit.
* We could implement a S3 file listing function (e.g. collect all datasets). Updates to S3 could automatically trigger this to rerun, or we could have a manual trigger (e.g. nextstrain.org/charon/rebuildAvailable).
* We could keep the status quo (JSON manifest on S3)

Anyone have opinions on these options? (No super hurry here, the status quo is ok)

### The static site (and other repos)
Currently the static (gatsby) site is built completely independently of this. 
This isn't great for testing etc, but it's possible to do.
Going forward, we will probably have more repos as part of "nextstrain.org", for instance the cloud augur frontend.
To improve things going forward we could:
* could make the "other" repo a dependency of this repo, such that building this repo builds that one also (e.g. the way auspice is done). Development could use `npm link` or similar. Not super clean but should work.
* merge the two repos into one
* git submodule _despite my dislike of submodules, this may be my preferred option at the moment!_

Anyone have opinions on these options? (No hurry on this one)

**Comment by tsibley** [comment]
I aim to digest and comment on this and other white-labeling stuff next week.

**Comment by tsibley** [comment]
> This allows nextstrain to pin a version of auspice, and decouples auspice releases from nextstrain.org releases.

:+1: This is a standard practice that would be great to do.

> Available datasets

I'm for having a generated manifest of some kind (as opposed to a manually-maintained manifest) stored alongside the datasets. It could be generated on-the-fly (a directory listing) or automatically updated as part of `nextstrain deploy`.  I think it's beneficial to separate the release of updated/new datasets from the release of updated nextstrain.org code. 

> The static site (and other repos)

I'm inclined to merge the current `static` repo into `nextstrain.org` and develop "cloud Augur" functionality there as well.  I don't see the advantage of separate repos in this case.

In general, I find that reaching for submodules is often a sign that the repos are either too splintered (and should just be combined) or that they should be imported as toolchain dependencies instead.  This is especially true if there is only a single consumer of the submodule/dep.  If we do want to go with a submodule-like approach, I've found [`git subrepo`][] to be a much nicer alternative which avoids a lot of the submodule papercuts.  `npm link` feels a bit like a hack in between a proper dep and a vendored submodule/subrepo.

[`git subrepo`]: https://github.com/ingydotnet/git-subrepo#readme

**Comment by jameshadfield** [comment]
Closing as we have since 
* moved the static site into this repo 🎉 
* are using `auspice` to build a customised nextstrain.org version 🎉 
* haven't modified the available datasets JSON as this is not pressing
