### ISSUE TITLE
action to release new versions of auspice

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#421]
_This issue also applies to [auspice.us](https://github.com/nextstrain/auspice.us/)_

Releasing new versions of auspice is a chore and often means auspice.us is behind the latest version. The current process, for each repo, is:

1. Checkout a branch, often called `next`
2. Update the auspice version in `package.json` (we pin to the exact version, as dependency management is hard and this ensures we have the version we want.) 
3. `npm install`
4. `npm run build` 
5. Test locally
6. Push branch & create PR
7. Test heroku review app (which has run steps 3 and 4 itself as part of its setup)
8. Merge PR & wait for site to automatically rebuild (each watches its respective GitHub repo's default branch)
9. Test website / monitor for server errors

An action could be created with a user-input for the auspice version desired. This action would then perform steps 2, 3, 4 and 6. We would then end up with a PR to test (via the review app) and then merge. 

As a stretch goal, the auspice release process could one day trigger this action, however this must happen _after_ the version has been deployed to npm. I looked for npm hooks we could attach a `workflow_dispatch` to, but couldn't find any. Alternatively, the action could be triggered immediately, and then poll `npm` to see when the new version is available; the release should be well within the GitHub actions time limit.

**Comment by victorlin** [comment]
Isn't this similar to what @ivan-aksamentov already implemented for Nextclade, e.g. nextstrain/nextclade#588? The same workflow could be used for all in-house downstream dependencies on auspice (`nextstrain.org`, `auspice.us`, `clades.nextstrain.org`).

**Comment by ivan-aksamentov** [comment]
Yes, that's basically a dependabot for 1 package. I just did not want to bother with figuring out how to configure dependabot for 1 dependency (if possible at all).
https://github.com/nextstrain/nextclade/blob/master/.github/workflows/Update-Auspice.yml

It's easier for Nextclade, because it's a static app, and PR deployments are easy with Vercel. Looks like there is the same thing with Heroku: https://devcenter.heroku.com/articles/github-integration-review-apps Might be a bit costly, but probably nothing compared to our AWS bills.

**Comment by victorlin** [comment]
Looks like Heroku PR review apps are already being used by [nextstrain.org](https://github.com/nextstrain/nextstrain.org/pull/429), [auspice.us](https://github.com/nextstrain/auspice.us/pull/15), and [auspice](https://github.com/nextstrain/auspice/pull/1432).

And your workflow is working well for the latest auspice bump to 2.32.1: nextstrain/nextclade#604

So I think the easy solution here is to copy @ivan-aksamentov's workflow to the other repos, and make a note in internal docs to manually sync any future workflow changes.

**Comment by jameshadfield** [comment]
> So I think the easy solution here is to copy @ivan-aksamentov's workflow to the other repos, and make a note in internal docs to manually sync any future workflow changes.

Sounds great. That workflow is exactly what I was looking for, with only slight modifications needed (`npm` not `yarn`, need to pin to the exact auspice version, use the node version specific to each project etc). Thanks @victorlin & @ivan-aksamentov 

P.S. Victor I'll DM you the credentials for @nextstrain-bot

**Comment by ivan-aksamentov** [comment]
One flaw I just discovered is that the workflow in Nextclade keeps updating the PR every day, also appearing in notifications. Even if you close the PR, it will just pop up the next day. And there is no way to dismiss it or to skip a version. But not a big deal if we plan to merge every time there's a new version.

**Comment by victorlin** [comment]
Closed by #572 which uses dependabot for automatic PR creation. Note that manual review is still required as described in the original comment.
