### ISSUE TITLE
Unreachable GitHub community build results in uncaught error

### ISSUE THREAD

**Issue by victorlin** [nextstrain/nextstrain.org#439]
When GitHub is down, community builds are naturally unavailable. However, the error is uncaught and shows as a Heroku application error which only renders after a couple minutes of page loading timeout. This was apparent during [the recent GitHub outage](https://www.githubstatus.com/incidents/r5qrpp2f5fc0):

![image](https://user-images.githubusercontent.com/13424970/144163200-8767df7b-a53a-4ef5-a571-4a43fad65815.png)

### Proposed solution:

Catch the error gracefully and render a message similar to when an invalid user/repo/dataset is requested (example https://nextstrain.org/community/invalid-user/invalid-repo/invalid-dataset).

**Comment by tsibley** [comment]
The outstanding PR https://github.com/nextstrain/nextstrain.org/pull/141 from a while ago is also relevant, although got tangled up in caching issues and I never got back to it.

**Comment by victorlin** [comment]
This happens very rarely, but maybe worth revisiting in the future.
