### ISSUE TITLE
Revise deploy process

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#485]
Our current deploy process looks like this:

- Push to `master` to auto-deploy to nextstrain.org (after CI passes)

I'd like to revise it with a canary (staging) site:

- Push to `master` to auto-deploy to next.nextstrain.org (after CI passes)
- Nothing auto-deploys to nextstrain.org
- After kicking the tires on next.nextstrain.org, [promote](https://devcenter.heroku.com/articles/pipelines#promoting) from that staging phrase of [our Heroku pipeline](https://dashboard.heroku.com/pipelines/38f67fc7-d93c-40c6-a182-501da2f89d9d) to the main site.

The main benefits:

- We always pass through a staging phase where the new version is running on the canary site in the Heroku production environment but doesn't impact the main site yet. This is very useful for catching prod-only bugs.
- Deploys to the main site are very fast, since promotion is basically just a big file copy for Heroku (it re-uses the slug).

Considerations:

- [x] We'll want to make the env/settings of next.nextstrain.org and nextstrain.org basically identical. They should share sessions (like dev.nextstrain.org currently does), despite this being a way that the canary site can impact the main site.
- [x] We'll need to make sure our build process doesn't bake in any env that's different between canary/main, since promotion is just a copy of the same slug.
- [x] Since dev.nextstrain.org has been historically used for ad-hoc testing, we may want to keep that and instead use a new domain for the staging phase. Perhaps canary.nextstrain.org or next.nextstrain.org (my fave :upside_down_face:).

**Comment by tsibley** [comment]
Some [conversation is happening](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1646422166450619) on Slack.

**Comment by jameshadfield** [comment]
Fully supportive of this. Nextstrain's grown a lot since we implemented the current deployment. I've pushed for the wider group to be in the habit of using dev.nextstrain.org day-to-day, but as it is only loosely coupled to the production site this never got much traction. With these changes to deployment I'd hope we can all get in the habit of using the dev site a lot more, otherwise "kicking the tires on dev.nextstrain.org" isn't much different to testing locally or in a review app (auth excepted). 

> Since dev.nextstrain.org has been historically used for ad-hoc testing, we may want to keep that and instead use a new domain for the staging phase.

I'd suggest just this. It's really valuable to have a dev server to play with, even if it's not used for most work.

**Comment by tsibley** [comment]
> I've pushed for the wider group to be in the habit of using dev.nextstrain.org day-to-day, but as it is only loosely coupled to the production site this never got much traction.

Yeah, totally get this. One way to make it easier to use the canary deployment for day-to-day work is to support setting a bit on sessions (e.g. for internal team members) which automatically redirects those sessions from main → canary (until the person flips the bit back, does a log out/log in cycle, or pops into incognito mode). This means people who want to use the canary can choose to without having to remember to do so every time. The bit can be session-only, or we could easily persist it on the user if we want it to persist across log out/log in cycles.

> I'd suggest just this. It's really valuable to have a dev server to play with, even if it's not used for most work.

:+1: Sounds good to me.

**Comment by trvrb** [comment]
>One way to make it easier to use the canary deployment for day-to-day work is to support setting a bit on sessions (e.g. for internal team members) which automatically redirects those sessions from main → canary...
That's super clever and I'd definitely support this. It would help me personally to be forced to use the "canary" site rather than having to remember to do so.

**Comment by tsibley** [comment]
@trvrb Good to know! Would you want it to persist across log out/log in cycles for your user until you explicitly flipped it off?

**Comment by trvrb** [comment]
Yeah. I'd be okay having all my logged in sessions redirected to "canary" site. To avoid it, I would use different browser, logout of my Nextstrain session or use incognito.

**Comment by tsibley** [comment]
Results of [straw poll on naming](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1646865223797259):

![image](https://user-images.githubusercontent.com/79913/158908651-f7d00621-6c2a-4649-a894-f6241b66b8e2.png)

**Comment by tsibley** [comment]
I have next.nextstrain.org setup. nextstrain.org is still auto-deploying from GitHub for the moment. Will finalize things tomorrow.

Up above I wrote:

> They should share sessions (like dev.nextstrain.org currently does), despite this being a way that the canary site can impact the main site.

…but this is not quite right. While dev.nextstrain.org and now next.nextstrain.org share a Redis instance (where sessions are stored) and a secret used to secure sessions, actual sessions are not portable across the domains because the session cookie is limited to a single domain (e.g. just nextstrain.org or just next.nextstrain.org).

We can change this (and I think we should, modulo some concerns; see below) by explicitly setting `cookie.domain: "nextstrain.org"` in [our `express-session` config](https://github.com/nextstrain/nextstrain.org/blob/3f67a85cf338cb073459da7712f544d71744d2d2/src/authn/index.js#L198-L211), which [somewhat unintuitively will allow subdomains too](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#domaindomain-value). (I'd been under the impression that the leading dot, e.g. `.nextstrain.org`, was necessary to allow that, which was the case for ages with [RFC2109](https://datatracker.ietf.org/doc/html/rfc2109), but long since outdated by [RFC6265](https://datatracker.ietf.org/doc/html/rfc6265).)

The only concern with enabling portable sessions across all *.nextstrain.org is that those session ids will be sent to other services we host on subdomains, like docs.nextstrain.org and support.nextstrain.org, for instance. This is probably fine in practice since we "trust" those providers, but it does increase the surface area for potential session hijacking via cookie theft. The big mitigation is that these cookies are already HTTP-only, so JS injections on those providers (much much more likely) can't access the cookies.

**Comment by tsibley** [comment]
Resolved by #485.
