### ISSUE TITLE
Automatic redirect from main site → canary for users who opt in

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#492]
Make it easier to use our (upcoming) canary deployment (see #485) for day-to-day work by adding support for setting a flag on users (e.g. for internal team members) which automatically redirects their requests from main → canary (until the person flips the flag back or logs out (or uses incognito mode / different browser)). This lets people choose to use the canary without having to remember to do so every time. Persistence on the session is very easy, but persistence on the user is desired as more convenient/stable. It's only slightly more work.

Approaches for persistence on the user:

1. Use a Cognito group, e.g. `@canary`, `!flag/wants-next`, or something similar, to mark users. This works well with the intentional restrictions we've put on Nextstrain Group names and how they map to Cognito groups. (I've long assumed we'd use Cognito groups for internal things too, like designating nextstrain.org admins at some point.)
2. Store a per-user key in Redis (where sessions are stored) with the flag value, e.g. `flag:canary:user/${userId}` or something.

Both can be easily expanded to include other user flags in the future, like feature flags. Approach (2), however, ends up using lots of keys potentially as it scales and requires another query to Redis for each request.

Approaches for opting in and out:

- Initially this could be manual. That'd be fine.
- But eventually a button + current status on the website somewhere (e.g. on a `/flags` page) could be useful which could make a simple PUT request to set the value and/or POST to toggle for the current user.

Considerations:

- [x] Should this user flag affect non-browser API requests too or just web sessions? I'm inclined to think just web sessions, as there are other ways for an API client to opt-into canary usage (e.g. `NEXTSTRAIN_DOT_ORG` with the Nextstrain CLI). This would mean checking both the flag and the presence of `req.session` before issuing a redirect to the canary.

**Comment by jameshadfield** [comment]
Nice one! 

One consideration is nextstrain team members using nextstrain.org inside talks / presentations. If there is a problem with canary (which there will be, that's kind of the point 😉 ), we want a way to access nextstrain.org (e.g. a different browser). So this might rule out approach (1)?

**Comment by tsibley** [comment]
Ah, both approaches relate to user-level persistence, not session-level, as the former seems more desired from discussion in #485. Definitely agreed that there needs to be a way to switch away from canary. With user-level persistence, that means either a) logging out (several ways to do this) or b) toggling the bit on your user. If your talk requires your logged in user, then (b) is necessary and would definitely be quicker/easier if a button/endpoint existed to do it.

(The button/endpoint also means we can easily let collabs or anyone else choose to opt-in to canary (though not sure people would want to).)
