### ISSUE TITLE
Add groups url prefix

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#50]
A group name `abc` should be accessible via the URL nextstrain.org/groups/abc. 

We currently have one active group. Unsure whether to redirect this to the "new" URL or not, but this can be handled separately.

**Comment by tsibley** [comment]
Redirecting should be possible without breaking the existing URLs at all, and I think will be most consistent and leave less historical baggage for the future.

**Comment by jameshadfield** [comment]
Closed by #59
