### ISSUE TITLE
Contact 1-2 collaborators to experiment with "groups"

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#51]
Currently we have a single partner using our in-development alpha features for private datasets. This is being called "Nextstrain Groups" for now, although only internally. (There is no UI copy for this.)

We think Groups is a good direction to head in and can start to be a response to "How do I get my data on nextstrain.org?" But to explore this effectively with purpose, we need early partners who can use it and participate in a continuous feedback cycle with us.

Big questions here is who are the current or prospective collaborators who might be suitable (willing to use it, natural need for it, able to provide feedback)?

**Comment by trvrb** [comment]
Catherine Pratt and Nate Grubaugh seem like the obvious candidates to me. Also Justin Bahl.

**Comment by jameshadfield** [comment]
Contacted Rob (GLUE) & will keep you posted. Adam Lauring might be another candidate.

**Comment by tsibley** [comment]
Closing. We blew past this and already have a cohort of early Groups users to get this feedback cycle from.
