### ISSUE TITLE
User page to replace stub

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#52]
When logged in, clicking on your username in the top right nav leads to a very bare bones page that includes the list of groups you're in and a logout link. This was due to time constraints during initial implementation. We'd like to replace this with a user page that fits in with the rest of the site. To start with, it doesn't have to have any more content then it currently does. I think the URL should change from `/whoami` to `/users/<name>`. (The `/whoami` API endpoint still needs to stay for the client.)

**Comment by jameshadfield** [comment]
Closed by #71
