### ISSUE TITLE
Move seattleflu builds to a seattleflu (public) group

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#53]
Dogfooding of Nextstrain Groups for the Seattle Flu Study will be useful in finding concrete problems and annoyances.

- [x] Creation of new source in `auspice/server/sources.js` that is visible to all users (?)
- [x] Creation of (private?) S3 bucket
- [ ] Redirection in server.js for current `/seattleflu/*` paths to `/groups/seattleflu/*`
- [x] Copy JSONs from nextstrain-data (and staging?) to the new bucket
- [ ] After deploy: Remove JSONs from nextstrain-data (and staging?)

**Comment by trvrb** [comment]
This is a great idea. Current `/seattleflu/` paths are barely used. I'd be okay not worrying about redirect. All these builds can be public. I've dropped the sensitive census tract data from them.
