### ISSUE TITLE
How should separate sections be implemented

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#54]
Related to #49, it's clear that nextstrain.org will contain more "sections" than the two currently present (static & auspice, see #49). Note that there may be a better word than sections. How should they be implemented? 

If the sections are more complex than some simple HTML, then I would prefer they use React which is currently used in multiple areas of nextstrain. There are also questions about trying to keep styling consistent between these sections. 

We could develop sections more-or-less independently, and try to centralise the styles. Or we could develop a "main" app encompassing multiple sections and use code-splitting to achieve acceptable performance.

**Comment by tsibley** [comment]
As much as I don't like Gatsby, I do think it'd be possible to put all our new pages (user pages, group pages, data management pages, etc) into Gatsby as React pages. They would make web API calls to fetch information they needed dynamically.

The alternative is setting up another React project with shared components between it, the Gatsby doc pages, and the Auspice client customizations, which seems like an n+1 problem if Gatsby is going to stick around.

While I think it'd be kinda nice to have one unified app which can render a React component like `<Auspice …>` instead of routing to different bundles, Auspice currently isn't designed to support that and I think you (@jameshadfield) expressed a preference against that direction previously.

**Comment by trvrb** [comment]
It would be nice to move away from Gatsby, but this sort of wrapping may be the best immediate solution. I don't have any great ideas here.

We are on a 2y old Gatsby version and it may be that upgrading could smooth some things out.

**Comment by jameshadfield** [comment]
In general, I'm sympathetic to the n+1 problem. I understand gatsby has moved on a lot in the past ~2 years, however it was not an enjoyable experience to build the "static-site" the first time around. Unless there are specific reasons we _really_ want to use things gatsby gives you for "free" (graphql, hydration etc), then I propose a n=3 solution:

1. The splash page, user groups, new features etc as part of a single React project (within this repo) that makes API calls as needed.
2. `/docs/` built with gatsby as it currently is. In the future, this could change to any other documentation source / static-site-generator as desired.
3. Auspice as currently implemented. While this theoretically could be `<Auspice/>` we have worked hard to get auspice to the state it currently is and I don't want to keep changing this.

I'd be supportive if someone wants to update gatsby and report back on their experience building in some new pages into the "static-site" part of nextstrain.org.

**Comment by jameshadfield** [comment]
No concrete decision on this was made in today's meeting, however we agreed to implement certain (small and quick) features within the gatsby framework. Namely:

(a) Make the nextstrain.org splash page dynamically show tiles (each consisting of a typical "nextstrain" colour) for each group if a user is logged in.

(b) (if time allows) Implement a 404 page in conjunction with #49 which will change the routing logic to "default" to the static-site if the path doesn't look like it's a dataset / narrative to be visualised by auspice (i.e. the opposite of what we currently do). The current state of the 404 page can be seen at https://nextstrain.org/docs/x

(c) (if time allows) the functionality currently present in #46. This should be relatively simple as the proof-of-principle UI and API calls are already present in that PR. 

(d) (if time allows) #52

**Comment by jameshadfield** [comment]
Closing this as we've moved the docs out of gatsby and into RTD (docs.nextstrain.org) and the current status-quo of having the splash page, sars-cov-2 page etc in gatsby is working well (if a little overly complicated).
