### ISSUE TITLE
Clicking back on a Nextstrain group dataset loads core datasets

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/nextstrain.org#57]
Steps to reproduce:

Log into nextstrain.org with authentication for a specific Nextstrain group.
Go to that group's URL, e.g. nextstrain.org/{GROUP}. The datasets loaded are for that specific group.
Click on an available dataset
Click back in your browser. The datasets loaded are from Nextstrain core, but the URL is still for the group.

**Comment by tsibley** [comment]
I believe this is an underlying Auspice bug.

**Comment by jameshadfield** [comment]
Correct - this is https://github.com/nextstrain/auspice/issues/815
