### ISSUE TITLE
Community on GitHub datasets using Git LFS are unviewable

### ISSUE THREAD

**Issue by arodzh-sudo** [nextstrain/nextstrain.org#575]
After updating the ncov workflow to v12, our datasets are visible using the nextstrain view auspice/ command, but are not reachable at the [Github community build site](https://nextstrain.org/community/arodzh-sudo/ncov-puertorico/Puerto-Rico) after uploading the json files to our auspice folder. We've been updating the datasets since our PR was merged with no issues.

**Comment by tsibley** [comment]
Thanks for the report. This appears to be a regression due to a recent deployment that changed some internals.

The request for `/charon/getDataset` is getting a 500 and emitting this to the logs:

```
2022-07-20T18:06:41.304478+00:00 app[web.1]: [verbose]  [fetch] GET https://github.com/arodzh-sudo/ncov-puertorico/raw/main/auspice/ncov-puertorico_Puerto-Rico.json (cache: no-cache)
2022-07-20T18:06:41.374931+00:00 app[web.1]: [verbose]  [fetch] 200 OK https://media.githubusercontent.com/media/arodzh-sudo/ncov-puertorico/main/auspice/ncov-puertorico_Puerto-Rico.json (cache miss, timestamp 2022-07-20T18:06:41.374Z)
2022-07-20T18:06:41.375287+00:00 app[web.1]: [warning]  Failed to fetch v2 main JSON: InternalServerError: source response has unacceptable Content-Type: application/octet-stream
2022-07-20T18:06:41.375417+00:00 app[web.1]: [verbose]  Sending InternalServerError: source response has unacceptable Content-Type: application/octet-stream error as JSON
2022-07-20T18:06:41.376733+00:00 heroku[router]: at=info method=GET path="/charon/getDataset?prefix=community/arodzh-sudo/ncov-puertorico/Puerto-Rico" host=nextstrain.org request_id=MASKED fwd="MASKED" dyno=web.1 connect=0ms service=150ms status=500 bytes=563 protocol=https
```

I understand the issue here and will try to deploy a fix shortly.

**Comment by tsibley** [comment]
Notably, this doesn't occur for all (most?) Community on GitHub datasets. The URLs for fetching the dataset files from GitHub (as returned by GitHub's API) are also structurally different and hit different GitHub hosts/endpoints. Compare:

    https://media.githubusercontent.com/media/arodzh-sudo/ncov-puertorico/main/auspice/ncov-puertorico_Puerto-Rico.json

    https://raw.githubusercontent.com/ktmeaton/yersinia-pestis/master/auspice/yersinia-pestis_maximum-likelihood_all.json

The latter is served with `Content-Type: text/plain`, which is acceptable to nextstrain.org's internals. The former is served with `Content-Type: application/octet-stream`, which is not (as seen in the logs above).

I wonder if this Content-Type difference is due to the different endpoint or if it's something more fundamental to the blob in the repo.

In any case, we need to account for it.

**Comment by tsibley** [comment]
The different endpoint is (as I suspected) due to Git LFS usage:

```
$ curl -sL https://raw.githubusercontent.com/arodzh-sudo/ncov-puertorico/main/auspice/ncov-puertorico_Puerto-Rico.json
version https://git-lfs.github.com/spec/v1
oid sha256:8944d443559409edc02b2a00b685790acf9ea35b9a3708d2053d1f7d4258a5bc
size 52592910
```

So the raw blob in the repo is actually just an LFS pointer to the blob in LFS.

**Comment by tsibley** [comment]
Looking at server logs for the past few days, there are at least several different Community on GitHub repos using LFS for dataset storage, and so this affects them too, e.g. https://nextstrain.org/community/andersen-lab/HCoV-19-Genomics-Nextstrain/hCoV-19/jordan.

**Comment by tsibley** [comment]
For internal context, this was also reported via [discussion.](https://discussion.nextstrain.org/t/unreachable-github-community-build-after-v12-update/1191/1) (public) and [hello@](https://support.nextstrain.org/support/nextstrain/ShowHomePage.do#Cases/dv/668036000002028027) (private).

**Comment by tsibley** [comment]
Deployed fix, confirmed on next.nextstrain.org, and promoted to production.

**Comment by arodzh-sudo** [comment]
@tsibley thank you for quick fix. 

Glad to know it was a LFS related issue rather than a ncov v12 update one.

**Comment by tsibley** [comment]
@arodzh-sudo One unrelated thing I noted while looking into this is that your dataset JSON is ~50MB. You can likely reduce that to ~8MB by using the `--minify-json` argument of `augur export v2`, which will help with page load times.

**Comment by AlbertRockG** [comment]
Hi @tsibley, I have a JSON file stored in Git LFS which `auspice` is can charge from my repository as a community build. So I tried to reduce the size of my JSON file with `--minify-json` as argument of `augur export v2` but it didn't work out as I still get a 171.3 MB JSON file. I did by modifying the shell script provided in the `main_workflow.smk` file and rerun my workflow after removing the results and the logs. Can you please help me sort this out please? Thanks.

**Comment by tsibley** [comment]
@AlbertRockG Hmm. That sounds like an issue with the workflow modification or something similar. To help you troubleshoot, we'd need to see the command and workflow you're running and ideally the final JSON file. Would you post those details to [discussion.nextstrain.org](https://discussion.nextstrain.org) so we can help you sort it out over there and not add a bunch of back and forth to this closed issue thread? Thanks.

**Comment by AlbertRockG** [comment]
Of course, thanks.
