### ISSUE TITLE
Scripts failing to work after CJS → ESM migration

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#591]
We overlooked the contents of `scripts/` in #583, so they no longer Just Work. This includes [things we run manually](https://github.com/nextstrain/nextstrain.org/pull/583#issuecomment-1254101185):

```
$ aws-profile blab/trs ./scripts/provision-group KU-song --members ~/Downloads/ku-song.yaml 
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /home/tom/nextstrain/nextstrain.org/scripts/provision-group
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at async Loader.import (internal/modules/esm/loader.js:177:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

$ head -n1 ./scripts/provision-group 
#!/usr/bin/env node
```

as well as [things we run automatically](https://github.com/nextstrain/nextstrain.org/actions):

![image](https://user-images.githubusercontent.com/79913/191587874-cf33b15c-bb48-444f-87a1-df5615be86cb.png)

```
Run ./scripts/collect-datasets.js --keyword flu
file:///home/runner/work/nextstrain.org/nextstrain.org/scripts/collect-datasets.js:2
const argparse = require('argparse');
                 ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/nextstrain.org/nextstrain.org/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/runner/work/nextstrain.org/nextstrain.org/scripts/collect-datasets.js:2:18
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    at async handleMainPromise (internal/modules/run_main.js:59:12)
Error: Process completed with exit code 1.
```

**Comment by victorlin** [comment]
Oof, I didn't realize these scripts were actively being used in relation to the top-level `package.json`.

We can use `cjs-to-es6` which I did in 1963fcd73db7f87e2f6f833ee448eb30136e300a to convert, then manually fix anything else.

@tsibley I can look into this today, unless you've already started.

**Comment by tsibley** [comment]
@victorlin No worries, it's not obvious! And we both overlooked it. Would be great if you could look into it though. :pray: I already made the minimum (and quickest) changes I could to `provision-group` so that I could run it without reverting things. I'll push that up as a draft branch and maybe a basis for a larger PR.

**Comment by tsibley** [comment]
Pushed https://github.com/nextstrain/nextstrain.org/commit/ca8b571487462f1818c8e93c93ba18ea1312b0e7 to [`fix-cjs-scripts`](https://github.com/nextstrain/nextstrain.org/compare/fix-cjs-scripts).

**Comment by tsibley** [comment]
Added 1d6131b to make the extension-less name work again, alleviating need to update external doc references.

**Comment by jameshadfield** [comment]
This [includes scheduled github actions](https://github.com/nextstrain/nextstrain.org/actions/runs/3101420771) which are failing. (We should rethink why we're running them,, but that's slightly tangential.)

**Comment by tsibley** [comment]
@jameshadfield Yep, see the screenshot in the original issue above. :-) (and indeed!)
