### ISSUE TITLE
static-site unbuildable under nodejs v16, v18 on darwin-arm64 aka M1

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#597]
### Current Behavior

Current master (d35785ed) under nodejs v16 or v18 (I can't conda install v14 on M1 architecture, but that's another matter)

The current setup is working on CI and on heroku, so it's not blocking. But it's a development pain. I'll try to debug, but posting here in case others have solutions!

```
$ npm run build --build-static

npm ERR! code 1
npm ERR! path /Users/enigma/projects/nextstrain/nextstrain.org/static-site/node_modules/sharp
npm ERR! command failed
npm ERR! command sh /var/folders/7w/rvnm5fgd7kb83fw8lg882x680000gn/T/install-23ce1806.sh
npm ERR! CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   TOUCH Release/obj.target/libvips-cpp.stamp
npm ERR!   CXX(target) Release/obj.target/sharp/src/common.o
npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-darwin-arm64v8.tar.gz
npm ERR! ERR! sharp Prebuilt libvips 8.9.1 binaries are not yet available for darwin-arm64v8
npm ERR! info sharp Attempting to build from source via node-gyp but this may fail due to the above error
npm ERR! info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.17.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.6 found at "/usr/local/opt/python@3.10/bin/python3.10"
npm ERR! gyp info spawn /usr/local/opt/python@3.10/bin/python3.10
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/enigma/miniconda3/envs/nextstrain.org/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/enigma/projects/nextstrain/nextstrain.org/static-site/node_modules/sharp/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/enigma/miniconda3/envs/nextstrain.org/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/enigma/Library/Caches/node-gyp/16.17.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/enigma/Library/Caches/node-gyp/16.17.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/enigma/miniconda3/envs/nextstrain.org/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/enigma/Library/Caches/node-gyp/16.17.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/enigma/projects/nextstrain/nextstrain.org/static-site/node_modules/sharp',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! ../src/common.cc:23:10: fatal error: 'vips/vips8' file not found
npm ERR! #include <vips/vips8>
npm ERR!          ^~~~~~~~~~~~
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/sharp/src/common.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/enigma/miniconda3/envs/nextstrain.org/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/Users/enigma/miniconda3/envs/nextstrain.org/bin/node" "/Users/enigma/miniconda3/envs/nextstrain.org/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/enigma/projects/nextstrain/nextstrain.org/static-site/node_modules/sharp
npm ERR! gyp ERR! node -v v16.17.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/enigma/.npm/_logs/2022-09-28T02_24_23_381Z-debug-0.log

Build failed at ./build.sh line 37

You are responsible for clean up (sorry!)
```

### Expected behavior

Build succeeded 😂 

### How to reproduce

You may need a M1 mac to reproduce this?

**Comment by jameshadfield** [comment]
### Possible solution

Replace gatsby

**Comment by joverlee521** [comment]
I also ran into this error when setting up my new laptop.

There are now [prebuilt binaries for sharp for darwin-arm64 since v0.29.0](https://sharp.pixelplumbing.com/install#apple-m1). However, some dependency in the static site forces sharp to downgrade to v0.25.4 when I try to install via `npm install sharp@0.29.0`. 

I found a [workaround for older versions of sharp](https://github.com/lovell/sharp/issues/2460#issuecomment-751491241), which is to install vips via homebrew to allow sharp to build from source.

**Comment by jameshadfield** [comment]
> I found a https://github.com/lovell/sharp/issues/2460#issuecomment-751491241, which is to install vips via homebrew to allow sharp to build from source.

@joverlee521 did you take notes on what steps you took? For me (apple arm64, rosetta not installes), I was able to install vips using homebrew (installed at /opt/homebrew/Cellar/vips/8.15.1_1) but this doesn't allow me to build sharp. I presume I need to supply the library paths as env variables or similar.

```
ERR! sharp Prebuilt libvips 8.9.1 binaries are not yet available for darwin-arm64v8
...
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
```

**Comment by joverlee521** [comment]
> @joverlee521 did you take notes on what steps you took? 

@jameshadfield, I didn't do anything special. I installed vips using homebrew (`brew install vips`) and then I was able to run `npm run build` without any issues...

There seems to be a mismatch in the vips version you installed (8.15.1) and the one shown in the error message (8.9.1) so for whatever reason it's not detecting the global installed vips. Try running `pkg-config --modversion vips-cpp` to see if it returns your expected version?

**Comment by jameshadfield** [comment]
Thanks @joverlee521 - I've actually deleted `vips` now and used #754 but if I return to this way I'll use `pkg-config` to explore. I don't have rosetta installed, and arm64 homebrew installs to `/opt/homebrew`, so at a guess I'd say this non-standard path is not being searched.

**Comment by victorlin** [comment]
#754 has hit a [dead end](https://github.com/nextstrain/nextstrain.org/pull/754#discussion_r1449528695).

I also checked if [gatsby-plugin-sharp](https://www.gatsbyjs.com/plugins/gatsby-plugin-sharp), the plugin that was mentioned in https://github.com/nextstrain/nextstrain.org/issues/597#issuecomment-1769026172, can be updated to pull down a version of sharp that comes with prebuilt darwin-arm64 binaries. That's also a dead end: 3.13.0 is the first version to depend on sharp 0.29.0, however 3.x depends on Gatsby version 3.

These are the current workarounds/solutions, from least to most complex:

1. Install `vips` via Homebrew. Works for myself and @joverlee521, but not @jameshadfield.
2. Apply changes from #754 as temporary patch during local dev.
3. Upgrade Gatsby to version 3 (also unblocks https://github.com/nextstrain/nextstrain.org/pull/698#issuecomment-1591790567).
4. [Replace Gatsby](https://github.com/nextstrain/private/issues/88).

**Comment by jameshadfield** [comment]
I'll get `vips` working together with sharp, using a thread on slack to help debug this. And I'll write up some notes when we're done that we can add to this issue / the install docs.

**Comment by jameshadfield** [comment]
Got it working :) I _think_ the magic step was to actually install `pkg-config` (via homebrew, for me), which I only did to run the command Jover asked me to.

```bash
brew install pkg-config
pkg-config --modversion vips-cpp # from jover
8.15.1
```
And after this the static-site correctly built for the first time (commit c3dd7262).

I'll add this to the docs on Monday and then close this issue.

**Comment by joverlee521** [comment]
> I think the magic step was to actually install pkg-config (via homebrew, for me)

Ah! `pkg-config` was already installed via homebrew for me as a dependency of `pyenv` so I didn't need to explicitly install it.
