### ISSUE TITLE
Is it possible to add `Neisseria gonorrhoeae` to the pathogen list

### ISSUE THREAD

**Issue by summercms** [nextstrain/nextstrain.org#609]
_###_ Context
How would this feature help you? What would it enable you to do?

Multi-drug resistant gonorrhoea seems to be the next greatest threat to the world and it would be great if next strain dot org added the list of XDR N.gonorrhoeae strains. Eighty-two million new cases of gonorrhoea occurred in 2020. So this is a major concern and I'm surprised it's not listed on the next strain website.

### Description
A clear and concise description of what you want to happen

Next Strain to add `Neisseria gonorrhoeae` to the pathogen list and include the [Antimicrobial-resistant gonorrhoea](https://www.eurosurveillance.org/content/10.2807/1560-7917.ES.2022.27.40.2200057) variants to help researchers track new XDR. Plus to help spend up the creation of gonococcal vaccines.

### Examples

Here's an example:

![image](https://user-images.githubusercontent.com/57409060/195465231-dae44012-0f51-46ea-9b35-c0f174cfc396.png)

### Possible solution
(Optional)

Various links of interest on the subject.

https://www.eurosurveillance.org/content/10.2807/1560-7917.ES.2022.27.24.2200455

https://www.eurosurveillance.org/content/10.2807/1560-7917.ES.2022.27.40.2200057

https://www.who.int/news-room/fact-sheets/detail/multi-drug-resistant-gonorrhoea

https://academic.oup.com/jid/article/225/6/983/6459455

**Comment by jameshadfield** [comment]
Hey @summercms - no one in the core Nextstrain team's working on AMR at the moment, but we'd be happy to help others in the community lead such an analysis. Nextstrain has been used for bacteria in the past so it's certainly possible, although the high level of recombination here will require some thought.
