### ISSUE TITLE
ENH: Update nextstrain.org auspice to v2.39.0

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/nextstrain.org#610]
I'm eagerly awaiting the bug fixes of our latest auspice release on nextstrain.org

Is there a reason why we haven't updated yet? :)

@jameshadfield @tsibley

**Comment by victorlin** [comment]
Auspice was updated on `master` with #604. `master` is automatically deployed to the canary app https://next.nextstrain.org so you should be able to see the bug fixes there. If things look good, we can promote to https://nextstrain.org. See [Infrastructure / Heroku](https://github.com/nextstrain/nextstrain.org/blob/6d84f1f91b72b8e47817e94bc9f035cc0062c7ad/docs/infrastructure.md#heroku) for more about the deployment process.

**Comment by corneliusroemer** [comment]
What's our deployment schedule - should we not promote more quickly? Maybe set a reminder to promote after x days?

It's been more than a week now, if no one tests next.nextstrain.org (wasn't aware this was possible) not much testing is happening anyways. So this just delays our features getting to users.

Maybe auto-promote after 7 days would be good?

**Comment by corneliusroemer** [comment]
Could we maybe make promotion a Github action too :) that would be neat...

I feel like the current delay is simply because no one could be bothered to deploy. Or is there a reason?

**Comment by tsibley** [comment]
@corneliusroemer 

> What's our deployment schedule - should we not promote more quickly? Maybe set a reminder to promote after x days?

Promotion is a judgement call by whoever merged the new code to `master`. Anyone merging should make sure the canary (https://next.nextstrain.org) still works fine after it's deployed and then decide to a) promote immediately to production or b) wait a bit to see if anything shakes out. This is a judgement call that depends a lot on the scope of the deployed changes.

A reminder (to #nextstrain-dev) of unpromoted changes would be good, but it's not something anyone's gotten around to yet. :-)

> Maybe auto-promote after 7 days would be good?

Eh, there is little harm in waiting a bit if changes get temporarily forgotten. I think auto-promotion would be more likely to cause breakage when no one's around. What we really care about is reducing time-to-promotion, and I think reminders would be a better way to accomplish that.

> It's been more than a week now, if no one tests next.nextstrain.org (wasn't aware this was possible) not much testing is happening anyways.

Several folks on the team routinely use https://next.nextstrain.org for daily work. If you want, [you too can join the Canary Club](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1655509816800599) and automatically be redirected to https://next.nextstrain.org from https://nextstrain.org when you're logged in. :-)

**Comment by tsibley** [comment]
Closing because James [promoted canary to prod yesterday](https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1665976472178079).
