### ISSUE TITLE
Move seattleflu datasets to a group & remove from core builds

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#68]
Currently seattleflu is set as a core build (i.e. accessable via nextstrain.org/seattleflu) with a TODO to remove this once #60 is merged (which it now is) https://github.com/nextstrain/nextstrain.org/blob/master/server.js#L114, however the datasets don't appear to have been added to the S3 bucket. 

I'm not sure about who has links to these URLs which will break as there are no redirects in place. 

@trvrb @tsibley can you comment on this when you've got a moment. It could be something that @kairstenfay tackles next week.

**Comment by trvrb** [comment]
It's okay if this never gets a redirect. The `/seattleflu/` URLs were never advertised.

**Comment by tsibley** [comment]
@jameshadfield I did almost all of this during our Nov dev week in #53, including moving data files around. Although something may have been reverted back since then?

**Comment by jameshadfield** [comment]
Not sure. https://nextstrain.org/groups/seattleflu isn't showing any datasets. I think this would be fantastic for @kairstenfay to work on unless it's just a button we haven't pressed somewhere.

**Comment by tsibley** [comment]
Ah, that's right. I recall running into that previously but had forgotten. Note that viewing a dataset works, https://nextstrain.org/groups/seattleflu/flu/seasonal/h3n2/genome/1y, it's just the listing of them.

**Comment by trvrb** [comment]
I'm closing this as the empty dataset list at https://nextstrain.org/groups/seattleflu is the same as https://nextstrain.org/groups/blab and represents a different issue. All the seattleflu JSONs have been moved to the `nextstrain-seattleflu` bucket.
