### ISSUE TITLE
ESLintError prevents running gatsby develop

### ISSUE THREAD

**Issue by trvrb** [nextstrain/nextstrain.org#689]
### Current Behavior

With the just merged linter rules update PR #688, I now get the following behavior. If I run:
```
cd static-site
rm -rf node_modules/
npm ci
npm run develop
```
I get the following error:
```
Generating development JavaScript bundle failed


/Users/trvrb/Documents/src/nextstrain.org/static-site/src/util/parseMarkdown.js
  55:32  error  Unexpected use of 'location'  no-restricted-globals

✖ 1 problem (1 error, 0 warnings)


File: src/util/parseMarkdown.js

failed Building development bundle - 7.859s
```

I can resolve the error either by commenting the line in question with `// eslint-disable-line` or I can revert back to 8570806b8836330ddf03f9c78be8ce415b6567d9 (before merge of #688).

@victorlin: Can you reproduce the issue?

### Possible solution
Restore the `// eslint-disable-line` at this line.

### Your environment: if running Nextstrain locally
 - Node: v19.8.1
 - npm: 9.5.1

**Comment by victorlin** [comment]
I can reproduce. Will create a PR to fix this.

**Comment by trvrb** [comment]
Awesome! I can confirm that PR #690 resolves this issue for me.
