### ISSUE TITLE
footer avatars don't wrap

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#72]
The avatars in the footer of the splash page (and docs pages) aren't wrapping, instead forming a very wide element in the page which isn't intended.

**Comment by trvrb** [comment]
Could you clarify James? I don't think I'm getting this behavior. If I size down to a narrow window (or look on my phone), I get the following:

<img width="511" alt="avatars" src="https://user-images.githubusercontent.com/1176109/71786850-605d2000-2fc5-11ea-850d-8c801e417a88.png">

**Comment by jameshadfield** [comment]
Hmmm. Firefox 71:

![image](https://user-images.githubusercontent.com/8350992/71786929-416a9680-3076-11ea-89f2-5ea7b33dd574.png)

![image](https://user-images.githubusercontent.com/8350992/71786935-4cbdc200-3076-11ea-8a61-48c4c3103dff.png)

**Comment by jameshadfield** [comment]
I'll take a crack at a fix. Should* be simple.
