### ISSUE TITLE
groups: Stop hardcoded assumption that group name matches source name exactly

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/nextstrain.org#76]
See @tsibley's [comments](https://github.com/nextstrain/nextstrain.org/pull/74#discussion_r364941068) on a [recent groups-related PR](https://github.com/nextstrain/nextstrain.org/pull/74) for context.

**Comment by jameshadfield** [comment]
@tsibley @kairstenfay could you elaborate on this here please?

We currently have a setup where nextstrain group `x` is backed by S3 bucket `nextstrain-x` and, if private, then authenticated users belong to the cognito group `x`. Are you suggesting moving away from this?

**Comment by tsibley** [comment]
@jameshadfield I'm suggesting that Nextstrain Group `x` being backed by Source `x` which is backed by S3 bucket `nextstrain-x` and Cognito group `x` is a temporary state in the implementation that we should bake into as little code as possible.

As I just mentioned in review comments on #82, we're missing a first class concept/object/record in the codebase for a Nextstrain Group. Sources are a distinct concept, and I want to avoid conflating them with Groups. For example, Groups have a Source (just one for now), but not all Sources are Groups. In the not too distant future, I think we need to introduce a proper Group concept, which knows which Source it is associated with (or, more likely, can dynamically instantiate that Source) and also knows other "group metadata" things, like what Cognito group it is associated with. The Group concept may still use our existing naming conventions, but it will be the sole place that is hardcoded and the rest of the system has those details abstracted away. The rest of the system will deal with Source objects (and the Group objects to-come) which have a consistent API. The design principle here is that components of the system should have clear ownership of data and actions related to them.
