### ISSUE TITLE
[CI] False positive build failures

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/nextstrain.org#794]
Our CI [monitors & reports the status of heroku builds for pushes to master](https://github.com/nextstrain/nextstrain.org/actions/runs/7821163186/workflow#L110-L129). Today's CI (triggered by the merge of #791) [reported a build failure](https://github.com/nextstrain/nextstrain.org/actions/runs/7821163186/job/21337674779), however the build succeeded ([heroku build log](https://dashboard.heroku.com/apps/nextstrain-canary/activity/builds/10967800-d10e-4612-b839-e340cb3ae077)).

The CI observed `"status": "pending"` which is not "succeeded" and thus the CI failed. I guess (?) this is caused by `curl` command returning before the build was actually finished. I haven't investigated further.

**Comment by tsibley** [comment]
Yeah, I saw this the other day too. I think we're racing Heroku's API here and inserting a short delay should probably make it Just Work again.

(That said, I do still want to #485 which in many incarnations would render this race non-existent.)
