### ISSUE TITLE
How to add years on x-axis using nextclade

### ISSUE THREAD

**Issue by sekhwal** [nextstrain/nextstrain.org#796]
I am using nextclade (https://clades.nextstrain.org/) for analysis of my Influenza HA nucleotide sequence, when I upload the fasta file and select reference " Influenza A H3N2 HA", in the tree it shows divergence on the x-axis but I need to add years on the x-axis instead. Please help me to figure out this.

**Comment by joverlee521** [comment]
Hi @sekhwal, 

Looks like your question was answered in the [Nextstrain discussion forum](https://discussion.nextstrain.org/t/how-to-add-years-on-x-axis-using-nextclade/1550/2?u=joverlee). 

If you have any questions about Nextclade in the future, feel free to open an issue in https://github.com/nextstrain/nextclade

**Comment by sekhwal** [comment]
Hi,
My question is not answered in the Nextstrain discussion forum
<https://discussion.nextstrain.org/t/how-to-add-years-on-x-axis-using-nextclade/1550/2?u=joverlee>,
I am still waiting for the follow-up.

Thank you,

Manoj

**Comment by joverlee521** [comment]
Ah, I see you've also opened an issue in the seasonal-flu repo.  Continuing conversation in https://github.com/nextstrain/seasonal-flu/issues/147 since this is related specifically to running the seasonal flu workflow.
