### ISSUE TITLE
Tutorials for Zika and TB refer to deprecated augur export interface

### ISSUE THREAD

**Issue by huddlej** [nextstrain/nextstrain.org#83]
Both the [Zika tutorial](https://nextstrain.org/docs/tutorials/zika) and [TB tutorial](https://nextstrain.org/docs/tutorials/tb) as the user to use `augur export` which is no longer supported by augur v6. These example commands need to be updated to specify `augur export v2` and also use the single `--output` flag instead of `--output-tree`, etc.

**Comment by rneher** [comment]
thanks for spotting this. Such creep is precisely the reason why having many copies of the same thing is a bad idea. the tutorials are correct here: https://github.com/nextstrain/zika-tutorial/blob/master/Snakefile and here: https://nextstrain-augur.readthedocs.io/en/latest/tutorials/zika_tutorial.html

I suggest linking to those or ingesting the markdown file in some way...

**Comment by shanesfast** [comment]
It seems like this issue has already been resolved. 
Here are some screen shots from the tutorial pages for TB and Zika:

![TB Tutorial Page](https://i.imgur.com/jOtFUyZ.png)
![Zika Tutorial Page](https://i.imgur.com/8TmNlp5.png)

**Comment by jameshadfield** [comment]
Closing as the docs have been updated. (We still have the larger issue of having similar tutorials in different places, which I'm hoping to write a bit on shortly. cc @eharkins for context.)
