### ISSUE TITLE
Tutorials for Zika and TB refer to an outdated auspice interface

### ISSUE THREAD

**Issue by huddlej** [nextstrain/nextstrain.org#84]
The Zika and TB tutorials ask users to visualize their auspice JSONs either with `nextstrain view` or by copying the JSONs into a local auspice install and running `npm run dev`. This latter interface seems unnecessary now that users can install auspice from npm and run it directly.

The visualize the results sections for [Zika](https://nextstrain.org/docs/tutorials/zika/#visualize-the-results) and [TB](https://nextstrain.org/docs/tutorials/tb#visualize-the-results) tutorials should replace this JSON copying + `npm run dev` with a single `auspice view` command.

**Comment by jameshadfield** [comment]
Closed by #124
