### ISSUE TITLE
Unhelpful behavior when attempting to load a private dataset while not logged in

### ISSUE THREAD

**Issue by trvrb** [nextstrain/nextstrain.org#86]
Now, when a private dataset is requested (like https://nextstrain.org/groups/inrb-drc/narratives/ebola/2020-01-13-sit-rep-ENGLISH) when someone is not logged in, it results in a "error accessing that dataset" like so:

<img width="1258" alt="not-found" src="https://user-images.githubusercontent.com/1176109/72772186-1f196280-3bb8-11ea-8b40-9c909ab32de4.png">

This has resulted in confusion as we don't prompt that a login is in order. On Slack (https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1579308035001200), we discussed that this should work like so:
>it should prompt for login, acknowledging that the group/dataset exists but is restricted

**Comment by jameshadfield** [comment]
Fixed by 74277ec6cb55e9a29551b5fbce8b0ebeb9519977 -- bug was introduced when we moved groups to having a ` /groups` URL structure (#59).

**Comment by trvrb** [comment]
Thanks for fixing this James!
