### ISSUE TITLE
Unversioned resource listings are truncated

### ISSUE THREAD

**Issue by victorlin** [nextstrain/nextstrain.org#896]
### Current Behavior

When setting `versioned=false` on ListResources, the resources entries are truncated.

<img width="894" alt="image" src="https://github.com/nextstrain/nextstrain.org/assets/13424970/fd2b6219-2a7b-4a20-8abe-208271390333">

### Expected behavior

Resource entries should not be truncated.

<img width="857" alt="image" src="https://github.com/nextstrain/nextstrain.org/assets/13424970/2c63c141-9b18-4b2a-91a9-b676a8764487">

### How to reproduce

1. Go to https://next.nextstrain.org/staging
2. Observe bug

### Scope

This was introduced in 54be4d60c17e62d236ad95d10aff3895ca0a4553.

This affects `/staging` but not `/pathogens`. It may also affect work on #870 that uses unversioned resources.

### Possible solution

Fix the condition here to not return `w` on lack of `updateCadence`:

https://github.com/nextstrain/nextstrain.org/blob/2e4844e6472ef4c1cf3aebf366fd6901758f64c1/static-site/src/components/ListResources/IndividualResource.tsx#L22-L34

**Comment by jameshadfield** [comment]
> This doesn't affect /pathogens which is the only place where this component is used (as of now). It may affect work on https://github.com/nextstrain/nextstrain.org/issues/870 that uses unversioned resources.

the :bug: is visible on https://next.nextstrain.org/staging

**Comment by victorlin** [comment]
@jameshadfield oh I didn't realize ListResources was being used on staging with versioned=false, thanks!
