### ISSUE TITLE
"Next steps" links broken at bottom of /docs/bioinformatics/introduction

### ISSUE THREAD

**Issue by kairstenfay** [nextstrain/nextstrain.org#9]
The links in the "Next steps" section of https://nextstrain.org/docs/bioinformatics/introduction/ and https://nextstrain.org/docs/bioinformatics/introduction/ are broken.

The first page is built from https://github.com/nextstrain/nextstrain.org/blob/master/static-site/content/docs/02-bioinformatics/01-introduction.md

**Comment by jameshadfield** [comment]
Closed in the `docs-flow` branch
