### ISSUE TITLE
Canary deployment does not always reflect latest merged PR

### ISSUE THREAD

**Issue by victorlin** [nextstrain/nextstrain.org#935]
I just merged two PRs in this order: #914, #922. next.nextstrain.org reflected the latest #922 briefly before the slower build of #914 completed and overrode the latest changes from #922.

Deploy is done as the last step of CI (which is also CD in this case). You can see that the workflows started around the same time but [#914's](https://github.com/nextstrain/nextstrain.org/actions/runs/9701489517) was slower than [#922's](https://github.com/nextstrain/nextstrain.org/actions/runs/9701500332):

![image](https://github.com/nextstrain/nextstrain.org/assets/13424970/8be79379-60e9-4cd0-8205-42608a6b4e2d)

### Possible solutions

1. [Use `jobs.<job_id>.concurrency`](https://docs.github.com/en/actions/using-jobs/using-concurrency#using-concurrency-in-different-scenarios)
    - I think this can be difficult because the actual `deploy` step is quick and will not overlap in most scenarios. The overlapping happens during `build` but concurrency shouldn't be checked on that job – it'd still be good to have a complete build for each merged PR. Maybe having a separate `build` but then we wouldn't be deploying the same exact build that's being tested.

**Comment by tsibley** [comment]
We do use `concurrency` controls already:

https://github.com/nextstrain/nextstrain.org/blob/6b7f3543f722473de22cee0cc4e3869e9eec72ee/.github/workflows/ci.yml#L126-L127

but yeah, it's only on the job where it's not enough to prevent this. Note that Heroku's own builds suffer from the same failure mode (I've seen it more than once).

> it'd still be good to have a complete build for each merged PR. 

Why? I agree it'd be good to have a complete build for each PR while it's a PR, but not each _merged_ PR. Once something's merged, we've serialized it onto `master` and it would be fine IMO for `master` builds to be serial too and use `concurrency` with `cancel-in-progress: true`.

**Comment by victorlin** [comment]
Good point. Maybe it'd be simpler to set `concurrency` on the workflow level, specifying at most one active run per branch?

**Comment by victorlin** [comment]
How about using `cancel-in-progress: true` so that previous CI runs will get canceled on new pushes?

**Comment by tsibley** [comment]
Sure, we can try it out and see how we like it.
