### ISSUE TITLE
Reflect on order of group tiles

### ISSUE THREAD

**Issue by victorlin** [nextstrain/nextstrain.org#953]
## Context

The group tiles are displayed like this:

![image](https://github.com/nextstrain/nextstrain.org/assets/13424970/6edeac9c-f1f1-42bf-bdc9-860f14c86282)

@joverlee521 noted in https://github.com/nextstrain/nextstrain.org/pull/949#pullrequestreview-2170101869 that it may seem like we are preferentially displaying the groups in the first row when it's really just a direct reflection of order in [env/production/groups.json](https://github.com/nextstrain/nextstrain.org/blob/20e88d780ef737f21993c23a895a5557d3aa1894/env/production/groups.json#L271) which is roughly the order in which groups are added.

## Potential solutions

1. Add a note saying that the order is mostly arbitrary.
2. Use a less arbitrary ordering. Alphabetical (easy) or most recently updated (maybe not so trivial).

**Comment by victorlin** [comment]
I think sorting alphabetically would be an easy gain. There's no good reason to keep the order from [env/production/groups.json](https://github.com/nextstrain/nextstrain.org/blob/20e88d780ef737f21993c23a895a5557d3aa1894/env/production/groups.json#L271) and I can't imagine any users finding that order useful. Alphabetical could make it easier to find and see related groups (e.g. public/private pairs that share a prefix).

**Comment by joverlee521** [comment]
> Alphabetical could make it easier to find and see related groups (e.g. public/private pairs that share a prefix).

Totally support alphabetical sorting for this!
