### ISSUE TITLE
./scripts/get-resource-index-ref-matrix not producing the correct matrix

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/nextstrain.org#980]
Noticed in https://github.com/nextstrain/nextstrain.org/pull/979#issuecomment-2278891739

I ran the index-resources GH Action workflow on the `victorlin/fix-resource-indexer` branch, expecting it to upload as the new `v3.json`, but it [uploaded as `v2.json` instead](https://github.com/nextstrain/nextstrain.org/actions/runs/10327086205/job/28591692144#step:7:30). 

Looks like something went wrong in `./scripts/get-resource-index-ref-matrix` because the [produced matrix points to the `v2.json`](https://github.com/nextstrain/nextstrain.org/actions/runs/10327086205/job/28591681062#step:4:10).

**Comment by joverlee521** [comment]
I am able to replicate behavior locally:

```

export IS_WORKFLOW_CALL=false
export HEROKU_TOKEN=bogus
export GITHUB_EVENT_NAME='workflow_dispatch'
export GITHUB_REF='victorlin/fix-resource-indexer'
export GITHUB_SHA='fc5eac219950cb7de8ce639a1c37f535a9521ba9'

./scripts/get-resource-index-ref-matrix
[{"ref":"fc5eac219950cb7de8ce639a1c37f535a9521ba9","resource_index":"s3://nextstrain-inventories/resources/v2.json.gz"}]
```

The GITHUB_SHA and the `ref` in the matrix match, so something is going on with getting the resource index.

**Comment by joverlee521** [comment]
OH! It's because the `/env/testing/config.json` was not updated as part of fc5eac219950cb7de8ce639a1c37f535a9521ba9. 
Without explicitly setting `NODE_ENV` or `CONFIG_FILE` envvars, the app defaults to using `/env/testing/config.json` which still pointed to `v2.json`.

**Comment by joverlee521** [comment]
Bumped the resource index version in `/env/testing/config.json` (https://github.com/nextstrain/nextstrain.org/pull/979/commits/da7f8eb110faaf56765a79a0378eea20157f2f3b) and the manually triggered workflow does [produce the expected matrix](https://github.com/nextstrain/nextstrain.org/actions/runs/10327521575/job/28592851906#step:4:10).

**Comment by joverlee521** [comment]
I can update the [resource-index docs](https://github.com/nextstrain/nextstrain.org/blob/ebe0d948e21ef91ec6769e2b339ce70963061385/docs/resource-collection.rst?plain=1#L25) to remind us to bump the version in both `/env/production/config.json` and `/env/testing/config.json`, but this could still happen in the future. 

`NODE_ENV` should probably be set to `production` within the `build-ref-matrix` job of the index-resources GH Action workflow.

**Comment by jameshadfield** [comment]
> I can update the [resource-index docs](https://github.com/nextstrain/nextstrain.org/blob/ebe0d948e21ef91ec6769e2b339ce70963061385/docs/resource-collection.rst?plain=1#L25) to remind us to bump the version in both /env/production/config.json and /env/testing/config.json, but this could still happen in the future.

If these are supposed to be updated in lockstep then we should add a check in CI that they are the same. And yes, please update the docs to point to the testing config!
