### ISSUE TITLE
Automatic redirects to translated narratives

### ISSUE THREAD

**Issue by tsibley** [nextstrain/nextstrain.org#99]
Do we want Auspice to support sets of translated narratives or do we hack this into nextstrain.org for nCoV specifically? Both are possible.

[Discussion in Slack](https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1580168034017500) leans towards hacking this into nextstrain.org just for nCoV for now.

The redirect can happen automatically, but should also allow manual switching. I imagine that we'll manually put comprehensive cross-links at the top of all dataset footers/start of narratives to other languages, at least as a start.

Later we could figure out a language chooser UI element somewhere else on the page generally.

**Comment by joverlee521** [comment]
Should automatic redirects happen through the `Accept-Language` HTTP header?

**Comment by tsibley** [comment]
Yes, at least until the user manually chooses a language. It would be good to follow [these best practices](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation#The_Accept-Language_header).

I don't know if there are browser APIs for parsing Accept-Language, but if not, I'm sure there are third-party ones.

**Comment by tsibley** [comment]
(and in general, this is usually part of a process called _content negotiation_ between the server and client, which also includes things like choosing content-type, e.g. between `text/html` and `application/json`.)

**Comment by joverlee521** [comment]
Should automatic redirect happen even if a user goes to a specific translated narrative?
For example, my language is set to `zh` but I got to `narratives/ncov/sit-rep/es/2020-01-25`, should it still redirect to `narratives/ncov/sit-rep/zh/2020-01-25`? Or should redirect happen only from the default English narrative?

**Comment by jameshadfield** [comment]
FYI @joverlee521 see changes in https://github.com/nextstrain/nextstrain.org/pull/105, although don't think any affect this work directly.

**Comment by tsibley** [comment]
After talking thru this with @joverlee521 yesterday, we decided it makes sense to first figure out a language selector and only then implement automatic redirects based on detected browser-expressed language preference. The reasoning is that if we get the language pref detection wrong, there's no way to switch to a language you read without a language selector.

**Comment by tsibley** [comment]
![IMG_5230](https://user-images.githubusercontent.com/79913/73488094-19acdc80-435d-11ea-9293-2475e9780f38.jpg)

Whiteboard from one approach to redirection.

**Comment by jameshadfield** [comment]
Closed by #110
